### ISSUE TITLE
App window completely transparent

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2171] opened 2017-05-04 05:30 UTC
A Windows user is reporting that the main app window is completely transparent. They already tried reinstalling and clearing the local db, nothing helped. 

![toggl desktop not working](https://cloud.githubusercontent.com/assets/19473351/25691468/95408c5c-309b-11e7-9a0f-20e1e4e86c80.jpg)

---
Case: 460087

**Comment by IndrekV** [comment] 2017-05-05 08:52
Probably issue with config file corruption. 
Clearing everything from folder
```
C:\Users\[user]\AppData\Local\Toggl\
```

should do the trick. @vedr4n I answered the user.

**Comment by fonorobert** [comment] 2017-05-10 18:29
@IndrekV user is reporting the issue is still present after clearing the local folder.

**Comment by kadrihvl** [comment] 2017-05-22 19:37
User is still struggling with this issue - @IndrekV any other suggestions? Case #460087

**Comment by TheSoloJake** [comment] 2018-06-27 18:37
Desk case/727074 is experiencing this issue, even after multiple uninstalls/cache clears/reinstalls of the latest stable version (.184). 

Windows version: 10, version 1803
Device: Surface Pro 3 (w/multiple displays, if that helps)

**Comment by IndrekV** [comment] 2018-07-12 19:06
duplicate of #2208
See this comment for possible workaround
https://github.com/toggl/toggldesktop/issues/2208#issuecomment-404445700

**Comment by IndrekV** [comment] 2018-08-22 10:45
closed together with #2208

**Closed by IndrekV** 2018-08-22 10:45 UTC
Labels: windows
