### ISSUE TITLE
Mac App: Text Box Highlighting Issue 

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2903] opened 2019-03-28 19:25 UTC
### 💻 Environment

Platform: MacOS
OS Version: 10.14.2
Toggl Version: 7.4.365

### 🐞 Actual behavior
Text box highlighting "jumps" when editing a time entry description or project assignment. Clicking on the project or description area in the edit screen "jumps" the highlighting to the "What Are You Doing" area

### 💯 Expected behavior
Clicking on a text box should keep focus/highlighting on that box until finished

### 📦 Additional info
Screenshot video of the issue can be found here: https://drive.google.com/file/d/1q0IabYtncWcSN61uIudWPxjQMYbwF5Kv/view?usp=sharing 

(link only available while logged into TogglGoogle account)

[convo](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21396232689)

**Comment by IndrekV** [comment] 2019-03-29 04:09
Duplicate of #2855. Is already fixed but not released.

**Closed by IndrekV** 2019-03-29 04:09 UTC
Labels: bug, macOs
