### ISSUE TITLE
List of entries scrolls down when new entry is started - OSX

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2109] opened 2017-01-19 14:27 UTC
osx_native_app/7.4.7 logs: #414868
User reports: 
There seems to be a small malfunction of ToggDesktop. Every time I finish time entry and start a new one the list of entries scrolls down to the oldest one (12 Dec 2016).
Clearing app's cache did help briefly, then this bug reappeared.

**Comment by IndrekV** [comment] 2017-02-03 12:52
This is like this a bit by design. When there is a running timer and new is started the list is updated with a new item and this resets the list making it scroll to the top.

**Comment by EvNaverniouk** [comment] 2017-02-27 21:47
I've just started noticing this recently too. It makes sense for the app to scroll to top, but this bug is causing the list to scroll all the way to the bottom.

**Comment by IndrekV** [comment] 2017-03-03 13:20
We've made some fixes to the scrolling logic. This issue should be fixed in latest stable (7.4.18)

**Closed by IndrekV** 2017-03-03 13:20 UTC
Labels: macOs
