### ISSUE TITLE
Mini Timer Goes Behind Taskbar In Win

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#2424] opened 2018-04-05 09:59 UTC
A user reported that (CASE #670463) the Mini Timer does not stay on top of the taskbar in Windows if the taskbar is clicked. 

I guess it's convenient for them to keep the timer there when something else is in full screen, but clicking on the taskbar will put the timer behind it, I did reproduce the issue (if this is an actual issue) in case it's something we can change in future: https://screencast-o-matic.com/watch/cFfhQNDd2D

**Comment by skel35** [comment] 2019-07-11 12:35
Duplicate of #2045

**Closed by skel35** 2019-07-11 12:35 UTC
Labels: windows
