### ISSUE TITLE
Desktop app missing dependencies on Ubuntu 16.10

### ISSUE THREAD

**Issue by hsdhillon** [toggl/toggldesktop#2034] opened 2016-10-28 21:02 UTC
I just upgraded to Ubuntu 16.10 and found out that Desktop app cannot be installed on 16.10 due to missing dependencies.

Below is the dump of dpkg while attempting the installation with toggldesktop_7.3.346_amd64.deb

```bash
Preparing to unpack toggldesktop_7.3.346_amd64.deb ...
Unpacking toggldesktop (7.3.346) over (7.3.326) ...
dpkg: dependency problems prevent configuration of toggldesktop:
 toggldesktop depends on libgstreamer-plugins-base0.10-0; however:
  Package libgstreamer-plugins-base0.10-0 is not installed.
 toggldesktop depends on libgstreamer0.10-0; however:
  Package libgstreamer0.10-0 is not installed.

dpkg: error processing package toggldesktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for bamfdaemon (0.5.3+16.10.20160929-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu4) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 toggldesktop

```

**Comment by IndrekV** [comment] 2016-10-29 08:48
duplicate of #1894

Current workaround is :

https://github.com/toggl/toggldesktop/issues/1894#issuecomment-254427913

**Closed by IndrekV** 2016-10-29 08:48 UTC
Labels: linux
