### ISSUE TITLE
Windows app UI fail

### ISSUE THREAD

**Issue by lremy** [toggl/toggldesktop#1382] opened 2015-06-23 07:17 UTC
Hi there,

My toggl-desktop recently updated itself (2015/06/22 I think).
According to ToggleDesktop.exe.config, Version=4.0.0.0.
I'm using Windows 8.1.
It's a laptop with screen resolution=3200*1800.

Here is the problem:
![togglmain](https://cloud.githubusercontent.com/assets/11176362/8300742/5d6a3b1a-1988-11e5-9570-b6652da727bb.PNG)
![toggldetails](https://cloud.githubusercontent.com/assets/11176362/8300744/5fcb7798-1988-11e5-81d1-25a10f984f1b.PNG)
![togglpreferences](https://cloud.githubusercontent.com/assets/11176362/8300746/6196eb52-1988-11e5-8d3b-88f35cd99ed6.PNG)

I don't think there's much more to say!
Is there any config or something I can do to correct the overall UI?

Thanks for any feedback!

Laurent

**Comment by amulware** [comment] 2015-06-23 07:41
Hey Laurent,

Thanks for the detailed report!
We have already heard similar things from other users, and are by now sure that this has to do with DPI scaling of high-density monitors (your high resolution confirms that).

We are not yet sure why the problem is occurring, but will continue to look into this.

The only thing you could try right now is disable DPI scaling for Toggl Desktop. See here on how to do so:
http://ccm.net/faq/32589-windows-8-1-disable-display-scaling-on-high-dpi-settings
That SHOULD work, but will most likely also make the window very small.

Sorry about the inconvenience!

**Comment by amulware** [comment] 2015-06-23 08:21
Closing as duplicate of  #1379.

**Closed by amulware** 2015-06-23 08:21 UTC
Labels: bug, windows

**Comment by lremy** [comment] 2015-06-23 08:38
Just a quick comment on disabling DPI scaling.
It almost works, except for some details (times and main duration).
Window is not small, so it's better like that.
![togglmain2](https://cloud.githubusercontent.com/assets/11176362/8302076/f5a1514c-1993-11e5-8428-816f3384b4b4.PNG)
![toggldetails2](https://cloud.githubusercontent.com/assets/11176362/8302077/f6e84cd6-1993-11e5-995a-e432fb3d9860.PNG)
![togglpreferences2](https://cloud.githubusercontent.com/assets/11176362/8302078/f8566e2c-1993-11e5-89d9-c6ceb7a24cc7.PNG)

**Comment by amulware** [comment] 2015-06-23 08:47
Thanks for reporting back.
Good to see that this works at least for the most part.

Hope to have this all sorted out and working the way it should for everybody soon!
