### ISSUE TITLE
wrong description/task/project selected when using autocomplete feature in new version

### ISSUE THREAD

**Issue by matthiaswagnerwy** [toggl/toggldesktop#2440] opened 2018-05-04 11:34 UTC
hy, 
i am using version 7.4.140 (beta) on mac right now and when i want to enter new times, i usually rely on the autocomplete-feature to select descriptions already entered earlier.
since the last update this fails - another description/task/project will be used instead. and sometimes "Missing GUID" appears above the timer bar.

hope this helps for development ;)
matt

**Comment by IndrekV** [comment] 2018-05-06 19:07
I think this is duplicate of #2435 
It's already fixed but not released. We'll try to get out new beta next week.

**Closed by IndrekV** 2018-05-06 19:07 UTC
Labels: bug, macOs
