### ISSUE TITLE
Toggl Mac Desktop Not Syncing with Toggl Server 

### ISSUE THREAD

**Issue by epicallan** [toggl/toggldesktop#2720] opened 2018-12-20 06:50 UTC
### 💻 Environment

Platform: macOS
OS Version:  macOS 10.14 (Mojave)
Toggl Version: 7.4.321

### 🐞 Actual behaviour

I have time entries in Toggl desktop that are not available on Toggl web dashboard.

### 💯 Expected behavior
Time entries on the desktop app should show on the web app

### 🔨 Steps to reproduce

1. Add a time entry on the desktop app
2. Do a manual sync
2. Then check the toggl web app

**Comment by IndrekV** [comment] 2018-12-20 09:09
This is fixed with the latest beta (7.4.330) that we just released. The issue was that when app lost connection to the network it would fail to reconnect and start syncing again. Thank you for pointing this issue out. Just switch to beta channel from the About view and let the app download an update.

Thank you for taking the time to report this.

Duplicate of #2685

**Closed by IndrekV** 2018-12-20 09:09 UTC
Labels: macOs

**Comment by epicallan** [comment] 2018-12-20 09:11
Ok, thanks
