### ISSUE TITLE
Project text box loses value while creating a new running Time Entry

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2597] opened 2018-10-22 06:54 UTC
Case 19137589717, on macOS app:

_(1) Click the START button_

_(2) Click the words "(no description)" to pop out the edit panel_

_(3) Begin typing in the "What are you doing?" field. The autocomplete choice I want appears in the autocomplete panel below._

_(4) Click on my autocomplete choice with the mouse. The Description field fills in with my autocomplete selection, but not the Project field. (I think the Project field should also fill in at this point, but that's not why I'm writing.)_

_(5) Press TAB. The Project field fills in with my autocomplete selection._

_(6) Now click at the end of the text in the Description field (because I want to add more text to the end of the string). *The Project field clears.* I think this is the wrong behavior. In Step 4 I affirmatively indicated that I wanted to select that Project, so the default behavior at this point should be to *keep* the value in the Project field, even though I haven't formally confirmed it yet._

(I also think the Project textbox should be filled when autocomplete is selected as well.

**Comment by IndrekV** [comment] 2018-11-09 03:37
duplicate of #2596

**Closed by IndrekV** 2018-11-09 03:37 UTC
Labels: bug, macOs
