### ISSUE TITLE
Windows Autocomplete

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2501] opened 2018-06-25 01:33 UTC
User reports needing to select the auto-complete option a second time, before it will populate the description and project fields.

Video of behaviour in case/726756

**Comment by Michelle112** [comment] 2018-06-25 14:09
In response to Nick's question of "if you press stop before selecting the previous entry a second time, whether the entry populates with the description and project or remains blank?" the user replied "Yes and no, it doesn't matter. If I've started the software fresh or if I pressed stop before. The behaviour seems the same."

**Comment by IndrekV** [comment] 2018-06-25 15:34
In the video user selects project from the description dropdown. I'm not able to reproduce this in the development branch so chances are one of the fixes I've done since release has already fixed it. I'll let you know when new beta is out so we can suggest the user to try and see if it is indeed fixed.

**Comment by IndrekV** [comment] 2018-07-05 14:22
new beta is out. I'll close this. Please open new issue if this still comes up.

**Closed by IndrekV** 2018-07-05 14:22 UTC
Labels: windows
