### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by msvendsen** [toggl/toggldesktop#1430] opened 2015-07-24 11:35 UTC
Hi,

I've some issues with the Toggl Desktop application. It seems to be a rendering issue. Instead of task list, I almost always see content from other open applications. If I resize Toggl Desktop, task list re-appear... until focus is on other applications. Have you seen this behaviour before?

**Comment by amulware** [comment] 2015-07-24 11:41
Hey, thanks for reporting the problem!

This is a known issue and already fixed in the current beta version.

If you would like to get the fix right now, you can switch to the beta in the about window of the application, wait a few minutes for the app to download in the background, and then restart it. The beta also comes with a number of other improvements, if you are interested.

Otherwise, we will most likely release the fix for everybody next week.

Closing this as duplicate of #1375.

**Closed by amulware** 2015-07-24 11:41 UTC
