### ISSUE TITLE
Make it possible to create Tags within Linux Desktop app

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggldesktop#2193] opened 2017-06-12 07:53 UTC
This is currently not possible, a user submitted a Feature request to make this possible in some of the future versions:

>Is not possible to add/create tags in linux version yet and the edition panel of timers could be improved. Any plans for these changes be implemented? 

Case: #485175

**Comment by IndrekV** [comment] 2017-12-14 23:39
duplicate of #1973

**Closed by IndrekV** 2017-12-14 23:39 UTC
Labels: enhancement, linux
