### ISSUE TITLE
Toggl Desktop invisible when disconnecting external screens

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1128] opened 2015-02-11 10:53 UTC
Toggl Desktop is visible on an external screen and when disconnecting the screen Toggl Desktop is not able to reposition itself to another screen.

**Comment by Richtor** [comment] 2015-02-19 22:43
You can work around by right click > Move then use the arrow keys and mouse to move it back onto a visible screen.

**Comment by amulware** [comment] 2015-09-16 17:55
Assigning to myself so I can see if this still occurs.

**Comment by amulware** [comment] 2015-09-28 12:11
Cannot reproduce the problem in current build. I suspect that WPF handles this by default, moving the window from one screen to the other, if it becomes invisible.

**Closed by amulware** 2015-09-28 12:11 UTC
Labels: bug, windows
