### ISSUE TITLE
App crashes if window is closed and you select quit from tray menu

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1866] opened 2016-03-28 13:43 UTC
If you close the app windows and then try to quit the app from the tray icon menu the app crashed.

Case : `266628`

_Screenshot is from latest dev build version 7.3.309_

<img width="931" alt="win_not_responding" src="https://cloud.githubusercontent.com/assets/842229/14079116/f4c2d312-f503-11e5-94cb-40421f7b4b22.png">

**Comment by amulware** [comment] 2016-03-28 20:39
Duplicate of #1853.

**Closed by amulware** 2016-03-28 20:39 UTC
Labels: bug, windows
