### ISSUE TITLE
Problems editing description/project

### ISSUE THREAD

**Issue by vanderlee** [toggl/toggldesktop#2194] opened 2017-06-12 10:16 UTC
Since about 2 weeks or so, I'm continuously having problems editing the description and project for tasks.
I can open the panel for editing, type in a new text, then nothing happens.
Have to close the panel again, do the same edits and usually (though not always) the edited description or project updates.
We never had these issues before about 2 weeks ago.

**Comment by kadrihvl** [comment] 2017-06-12 10:30
Also reported by case #485311 (osx_native_app/7.4.11- will ask to upgrade, but the same behaviour seems to be reported by users on latest release as well).

**Comment by vanderlee** [comment] 2017-06-12 10:59
Using 7.4.38 and have been for about a week. Updated from a previous 7.4.3x which also had this bug.

**Comment by kadrihvl** [comment] 2017-06-12 11:02
@vanderlee have you reached out to us from app's Feedback form? We'd get app's logs with the note and it could be very helpful while debugging this.

**Comment by IndrekV** [comment] 2017-06-12 13:31
duplicate of #2183
@vanderlee 
There is a fixed version out there:

You can get the fixed version from: 
Mac: [TogglDesktop-7_4_45.dmg](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/TogglDesktop-7_4_45.dmg)

Windows:
[TogglDesktopInstaller-7.4.45.exe](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/TogglDesktopInstaller-7.4.45.exe)

Linux:
[toggldesktop_linux_x86_64-7_4_45.tar.gz](https://github.com/toggl/toggldesktop/releases/download/v7.4.45/toggldesktop_linux_x86_64-7_4_45.tar.gz)

**Closed by IndrekV** 2017-06-12 13:31 UTC
