### ISSUE TITLE
Edit view doesn't display all elements in high dpi setting

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1465] opened 2015-08-13 13:17 UTC
More info in case 181237

**Comment by amulware** [comment] 2015-08-13 13:33
This is caused by the WPF controls adapting to the high DPI (they get bigger in real pixels), while the window (winforms) does not adept.

Should be easily fixed by making the window check the DPI setting of the screen it is on, and resizing itself appropriately.

**Comment by amulware** [comment] 2015-08-28 13:31
The edit form has been converted to WPF in a8a4e1bac0241016470f94e322ef83b1a8bc7dd6.

However, for now this is not usable, since the main form is still WinForms, which scales differently (not) with DPI scaling. Once the main form is converted as well, this problem will be gone.

**Comment by amulware** [comment] 2015-09-08 09:21
Closing since all work for this is done. Will be merged into master soon.

**Closed by amulware** 2015-09-08 09:21 UTC
Labels: bug, windows
