### ISSUE TITLE
Stopping currently running task leads to visual errors

### ISSUE THREAD

**Issue by mdiener** [toggl/toggldesktop#1410] opened 2015-07-09 20:22 UTC
When I create a new task in toggle and then hit the stop button, nothing happens for a few seconds. After a while the just stopped task appears and moves the current tasks down, however, this only happens on the right side of toggl desktop. The left with times stays as before which create a weird looking experience. Once the window is redrawn (mouse moved over tasks, size changed, etc.) it is displayed correctly.

My workstation:
Windows 8.1
Intel Core i7-3820 3.6 GHz
NVIDIA GeForce GTX 660 Ti

**Comment by amulware** [comment] 2015-07-10 05:37
Thanks for reporting this, and for including your specs!

This is a known problem with the last version , and while we are not 100% sure what causes it, we will probably be able to release a new version including a fix soon.

Closing this as duplicate of #1375.

**Closed by amulware** 2015-07-10 05:37 UTC

**Comment by mdiener** [comment] 2015-07-10 15:10
Ugh and I was so sure I checked all the tickets. Sorry about the duplicate, I know that's annoying. I'll monitor ticket #1375 closely then.

Thank you for the very quick response!
