### ISSUE TITLE
UI glitches on windows

### ISSUE THREAD

**Issue by egoroof** [toggl/toggldesktop#1526] opened 2015-09-22 15:24 UTC
v7.2.313 (latest stable)
Windows 8.1 x64
Nvidia GeForce 9800 GT

When I continue/stop timer via global shortcut I see UI glitches (which are changing after mouse hover):
![2015-09-22 23 07 19](https://cloud.githubusercontent.com/assets/2605831/10022477/a9458028-617f-11e5-8c7c-d2363ffde3dd.png)
![2015-09-22 23 29 11](https://cloud.githubusercontent.com/assets/2605831/10022916/d18cf99c-6181-11e5-9f92-16705fcaca91.png)
It differs time to time: doesn't show description or doesn't change "Start" button to "Stop", etc.
I have latest graphical drivers. Don't see it in other software.

**Comment by adrianhalid** [comment] 2015-09-22 23:55
I too see a similar issue.

My working environment is a local Windows 8.1 install and a Virtual Windows 8.1 in the cloud.

I often work between these two machines on the local and then Remote Desktop into the Virtual Machine in full screen mode.

I run Toggl Desktop on both so I can easily change tasks no matter if I am using the Local Machine or the Remote machine.

There are slight UI Sync issues between the too.

For example when I change or stop/start tasks on one machine the UI of toggle is not updated on the other.

Here is a screenshot example of a task already running on my local machine and then I start toggle on the remote machine.

You can see that the title bar of the window correctly state Emails and Admin task but the task description box says "What are you doing?"

Resizing the window usually fixes the display issue.

![capture](https://cloud.githubusercontent.com/assets/12272329/10035005/63466c74-61c8-11e5-8193-68a86fa2b7ea.PNG)

**Comment by leup** [comment] 2015-09-23 09:52
Got this kind of UI glitches too. Sometimes the UI is freezing.

**Comment by amulware** [comment] 2015-09-23 17:53
Thanks for reporting the problem!

We have been busy rewriting the Toggl Desktop user interface on Windows the last few weeks. We just released a new beta version today, that exclusively uses the new framework we are switching to, and we believe that this should solve these glitches you noticed.

Could you try and see if the beta version works better for you?

You can switch to the beta in the "about" window of the app.
After you do, please give the program 5-10 minutes to download the update in the background, and then restart it. It will then install the update automatically.
If the update was successful, it will show the new version number in the about window: 7.2.348

Sorry for the inconvenience!

**Comment by egoroof** [comment] 2015-09-23 18:23
@amulware I've updated to 7.2.348 and don't see this glitches now. Thanks!
But there is a new issue - when I use global shortcut to continue timer it starts a new empty task (not continue old).

**Comment by IndrekV** [comment] 2015-09-23 18:33
@egoroof Thank you for reporting this I've created another issue for this bug #1531

**Comment by leup** [comment] 2015-09-23 18:54
Just to let you know that I had switched to the dev channel a few days ago. It seems that there is no more glitches as the ones reported here, but there is still some freezes of the UI. A few seconds everytime and it happens often. Should you/I creat a new issue for this ?

**Comment by IndrekV** [comment] 2015-09-24 06:31
@leup Could you please send us a screencast to support@toggl.com of the issue, so we can see how exactly the the glitches appear. Mention Paul in your email so it's redirected to us straight away.

**Comment by IndrekV** [comment] 2015-09-24 06:33
@leup Actually it would be good if you could just send feedback from the app, that way we get the log files and can investigate the source of the issue.

**Comment by amulware** [comment] 2015-09-28 10:00
Closing since original issue was resolved. We are continuing to collect data about performance issues, and hope to get the app buttery smooth for everyone in due time.

**Closed by amulware** 2015-09-28 10:00 UTC

**Comment by leup** [comment] 2015-10-08 09:19
The app is a lot more smooth now. Seeing no more UI glitches and no more freezes. Last thing remaining is that sometimes when focusing an input field like the task name nothing happen. It gives the feeling that something is wrong. But start typing anything and the focus appears on the field. It is just the lack of visual feedback that the focus has indeed been given to the field.

**Comment by amulware** [comment] 2015-10-08 09:21
@leup Thanks for reporting back!

I can reproduce the focus thing you mention. At least sometimes. No idea what is causing it, but we will definitely take a closer look.
