### ISSUE TITLE
Fails to install - depends on old libgstreamer

### ISSUE THREAD

**Issue by martysto** [toggl/toggldesktop#2460] opened 2018-05-26 14:16 UTC
Preparing to unpack toggldesktop_7.4.122_amd64.deb ...
Unpacking toggldesktop (7.4.122) ...
dpkg: dependency problems prevent configuration of toggldesktop:
 toggldesktop depends on libgstreamer-plugins-base0.10-0; however:
  Package libgstreamer-plugins-base0.10-0 is not installed.
 toggldesktop depends on libgstreamer0.10-0; however:
  Package libgstreamer0.10-0 is not installed.

dpkg: error processing package toggldesktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 toggldesktop

I think it should work with libgstreamer1.0-0 which is the default e.g. in Ubuntu 18.04.

**Comment by IndrekV** [comment] 2018-05-28 06:45
duplicate of #1894

**Closed by IndrekV** 2018-05-28 06:45 UTC
Labels: linux
