### ISSUE TITLE
Text input refocussing

### ISSUE THREAD

**Issue by vanderlee** [toggl/toggldesktop#2028] opened 2016-10-26 13:06 UTC
The Toggl Desktop has the annoying habit of moving the focus of the text input at will.

**Reproduce:**
Start a task.
Stop the task.
Edit the task end-time.
Click on the black "titlebar" and start typing the new task name.

**Actual result:**
After typing a few characters of the new task name, Desktop moves the focus to the task name of the previous task and any characters typed appear at the end of the previous task's name.

**Expected result:**
I can continue typing the new task name, then press enter to have it start.

**Comment by IndrekV** [comment] 2016-10-26 13:14
Could you please specify the platform you are using.

**Comment by vanderlee** [comment] 2016-10-26 15:00
This is on Windows 10.

From what I see, it seems the of the "side panel" (where you can edit times) takes some time to process the change (communicating with the server, I assume), then moves the input focus afterwards.

**Comment by vedr4n** [comment] 2016-11-18 10:05
I can reproduce this problem, it is in fact specific to Windows. 

To reproduce

1. Edit an existing time entry (description is fine) and leave the edit screen open
2. Start typing into the "What are you doing" field
3. The text should jump from "What are you doing" to the description of the TE you just edited

This only happens when the edit screen is left open. If you close it (after editing the TE) there is no problem.

On macOS the app automatically closes the edit screen as soon as you click into the "What are you doing" field. 

I tested this with .349

**Comment by IndrekV** [comment] 2018-07-05 15:36
duplicate of #1995

**Closed by IndrekV** 2018-07-05 15:36 UTC
Labels: bug, windows
