### ISSUE TITLE
toggl desktop blurred on high-dpi Windows 8.1

### ISSUE THREAD

**Issue by wilhelmmedetz** [toggl/toggldesktop#1232] opened 2015-03-14 14:54 UTC
When starting toggl desktop (7.1.224) on a high-dpi Windows 8.1 (screen scaling set to 150%), toggl desktop becomes blurred (picture 1).

![picture1](https://cloud.githubusercontent.com/assets/7532446/6652078/b2cdcc00-ca61-11e4-9f2e-e06f7e723bc7.PNG)

When disabling display scaling for toggl desktop, toggl desktop is displayed sharp (picture2), also the font size of the main window looks good.

![picture2](https://cloud.githubusercontent.com/assets/7532446/6652079/b402fc62-ca61-11e4-8f19-113d949cb6ab.PNG)

There is one problem when disabling display scaling, the line height of the projects dropdown list in the details windows is small (picture3).

![picture3](https://cloud.githubusercontent.com/assets/7532446/6652080/b5d7ef0c-ca61-11e4-90df-0e20a006a44e.PNG)

**Comment by alpha-cast** [comment] 2015-06-25 00:17
Mine looks a little different, but it's still the DPI settings, and it's not really usable. I can't even see the time (Yoga 2 Pro 13"):

![toggl feedback](https://cloud.githubusercontent.com/assets/2695677/8344290/179a257c-1b23-11e5-8783-2e8c44e3957e.png)

**Comment by amulware** [comment] 2015-06-25 05:44
Could you confirm: Do you have display scaling enabled or disabled for Toggl Desktop?

See here for what I mean if unclear: http://ccm.net/faq/32589-windows-8-1-disable-display-scaling-on-high-dpi-settings

**Comment by amulware** [comment] 2015-06-25 05:45
Closing this as duplicate of: #1379

**Closed by amulware** 2015-06-25 05:45 UTC
