### ISSUE TITLE
Investigate timeline recording errors

### ISSUE THREAD

**Issue by amulware** [toggl/toggldesktop#1861] opened 2016-03-17 10:47 UTC
As a continuation of #1801 we should investigate, and try and reproduce the problems that some users have with recording their timeline. To resolve that issue we prevented errors to cause 'Unknown program' entries, however this means that some users now get only very little to no data in their timeline.

A log file posted in the same issue shows the occurrence of multiple errors (1, 4, 5, 6) for that user.

We may want to try and test timeline on multiple machines to see if we can find a pattern, to see what may cause the different errors.

**Comment by wefixitgr** [comment] 2016-03-17 13:06
Continuing the help on reproducing I'm attaching all the software installed on my pc (used ccleaner to export them all).
[install.txt](https://github.com/toggl/toggldesktop/files/177884/install.txt)

**Comment by odeland** [comment] 2016-03-23 16:33
I'm also using Toggl Desktop on Windows 8.1 (French Canada) and having the same issue with my timeline for a couple weeks now. It records for about 15 minutes every morning, then stops at around 9h00 (13h00 UTC)

The change I can see in the log is this line:

2016-03-23 13:00:48.261 [3804 6]:user:D:CompressTimeline done in 0 seconds, 31014 compressed into **0 chunks**

It should be 1 chunks, but instead it's compressing to 0 chunks. Does this give any clue? Let me know what kind of log can be useful here.

**Comment by kadrihvl** [comment] 2016-04-04 07:57
Cases that have reported this issue: #268642

**Comment by wefixitgr** [comment] 2016-04-04 08:11
As a side note, although its obvious, autotracker is also not working. Do we have any progress on this @amulware ?

I find myself going through browser history to remember what I was doing that day to log it down. :/

**Comment by amulware** [comment] 2016-04-04 08:14
We are still investigating and may release a new experimental build sometime soon.

**Comment by amulware** [comment] 2016-04-04 16:11
Looking over some log files, I notice a lot of lines like

```
2016-03-31 18:36:32.043 [5504 5]:user:D:CompressTimeline done in 0 seconds, 30022 compressed into 0 chunks
```

It may be that something goes wrong in the compression. At least it seems that with 30 thousand entries, something should be transmitted.

That number also only seems to go up, and never down, maybe old data is not cleared out properly.

**Comment by amulware** [comment] 2016-04-04 16:18
Different users also seem to get different combinations of errors. 1 and 4 are common to all logs I looked at, but 5 and 6 also happen regularly.

With the way we are recording these, it is difficult to know for how much of the problem they are responsible.

**Comment by IndrekV** [comment] 2016-04-05 13:24
I've created a new development build (7.3.310) with fixes. I would appreciate if someone would test it out and let me know if the issue is fixed. 

You can get it by changing channel to dev in the About view and waiting for the update to do it's work. 

Or you can download it from https://github.com/toggl/toggldesktop/releases/download/v7.3.310/TogglDesktopInstaller-7.3.310.exe 
and install it manually.

**Comment by wefixitgr** [comment] 2016-04-05 15:07
Thank you @IndrekV for the dev build. I installed it manually and already have some promising findings.

I've been using this version for an hour now with mixed results.
I can see on my timeline that reporting now works. It also identified my phpstorm window when it was active. Chrome still comes up as unknown program. Since I'm coding right now I can't report on other windows _yet_ but will come back tomorrow and report when I will have more data.

I noticed on the commit referenced above that you enabled more detailed logging. Do you prefer me to attach the logs here or to do it from the app by sending feedback and maybe writing this issue in the description?

**Comment by IndrekV** [comment] 2016-04-06 07:58
Thank you for the details. I would prefer if you would send feedback from the app and mention that it is for Indrek. That way I get logs and stuff to investigate.

Will test out the syncing issue also.

Thank you for testing out the fix.

**Comment by IndrekV** [comment] 2016-06-16 08:59
More details in case 275662

**Comment by TheLEAX** [comment] 2016-07-08 21:05
Hi guys! (came from issue #1801 ) Im a newbie soo... my 5 cents from today:
autotracker - only working with chrome tabs/actions , doesnt detect win programs
timeline - the same, showing only chrome actions, windows programs as "unknown program"

Win 8.1 Pro 64, tried stable and dev version = same results

I dont know which files to post but in one log ive found:
2016-07-08 20:52:08.326 [4572 5]:WindowChangeRecorder:E:Failed to get focused window info, error code: 299 [1500 times]
[toggldesktop.log.txt](https://github.com/toggl/toggldesktop/files/355114/toggldesktop.log.txt)

What files / logs should I further post to you to help you reproduce?

**Comment by wefixitgr** [comment] 2016-10-07 08:39
It must be a Windows 8.x problem, since upgrading to Windows 10 toggl autotracker works great.

**Comment by axsauze** [comment] 2016-12-04 12:02
Hey guys, I'm using a mac, I started using Toggl 3 days ago, but my timeline just doesn't work. I've followed all the recommendations - toggled the "Record Timeline" option, restart my computer, and none have worked.
I have the timeline enabled in my dashboard, but it still doesn't record anything.
How can I fix this?
Thank you.

**Comment by oshev** [comment] 2016-12-04 12:36
Hey! I'm also on Mac and have exactly the same problem. Thanks

**Comment by IndrekV** [comment] 2016-12-05 04:24
@axsauze , @oshev Please send feedback from the app so we can look into logs and see whats happening with the timeline tracking.

**Comment by oshev** [comment] 2016-12-08 21:40
Hi, Indrek! Thank you for your reply! I've sent a feedback from the app, mentioning the timeline there. I'm not sure what is exactly sent with the timeline, information about my OS and the computer? Do you need anything else to investigate?

**Comment by kadrihvl** [comment] 2016-12-09 08:29
@indrek - another similar report with logs and some details of programs not showing up.
Logs: https://toggl.desk.com/agent/case/394999 windows_native_app/7.3.337
>>>Some of my vertical bars gets populated with blank application names. I have too engineering software which I know is not recognized.
One is called "PTC Creo 2" and the other "Dassault system Abaqus".
http://www.ptc.com/cad/creo
http://www.3ds.com/products-services/simulia/products/abaqus/
The binaries for Creo is called Xtop.exe, and for Abaqus it is abqcaeg.exe.
Around 12:15 on the 8th Nov there should be a abqcaeg.exe record. Todaythere is three empty records.

**Comment by kadrihvl** [comment] 2016-12-15 08:30
User gives this example of missing timeline data:

> PHPStorm is not shown in the timeline, althought it is recorded as unknown. The program is phpstorm.exe, which in turn launches phpstorm64.exe. 

Logs with case #397888

**Comment by axsauze** [comment] 2017-01-23 14:49
Hey guys, my Toggl app still doesn't provide timeline information - this is a critical feature for me so I'm going to have to move to RescueTime or another app until this is solved... I'll be subscribed to this issue so I'll be alert - hopefully it can be fixed soon...

**Comment by kadrihvl** [comment] 2017-01-24 06:02
@axsauze - please let us know the email address connected to your Toggl account. We may need to switch it on from our side as well.

**Comment by hkalia** [comment] 2017-03-31 02:31
Perhaps this issue may be related to the new SIP feature on OSX and macOS?

**Comment by IndrekV** [comment] 2017-03-31 04:17
@hkalia Thank you for your feedback. All the issues reported are about windows we have not received feedback about tracking timeline info in MacOS. So I guess the SIP feature is not blocking this.

**Comment by mary-loulou** [comment] 2017-04-11 16:52
Win10Pro 64-bit: 
Autotracker is working just fine.
Timeline is not logging anything. :-( --> RescueTime is working just fine.
Any ideas why timeline is not working  at all?

**Comment by fonorobert** [comment] 2017-04-21 12:02
As @kadrihvl mentioned in some cases this can be caused by an issue on our end, not in the desktop client itself. If you email us, we can check and fix that user-by-user.

**Comment by odeland** [comment] 2017-06-09 14:07
It seems to me that Toggl Timeline is only tracking 32 bits applications on Windows. Chrome recently upgraded from 32 bits to 64 bits on my system and it's now showing as a blank entry in Timeline. I only see 32 bits applications in my Timeline. 

Is there anything that can be done about this here?

**Comment by ben-johnstone** [comment] 2017-06-24 17:44
I am not recording any timeline activity despite 'Record Timeline' ticked in my desktop App. The app syncs so I wonder if there's an issue with Windows 10 / Mcafee?

Ben

**Comment by TheSoloJake** [comment] 2017-06-24 22:28
@ben-johnstone Can you email support(at)toggl(dot)com with your Toggl account email address? We can look at turning on Timeline on our end. Thanks!

**Comment by IndrekV** [comment] 2019-07-11 03:44
Will be fixed with 64bit release.

**Closed** 2019-07-11 03:44 UTC
Labels: bug, lib, windows
