### ISSUE TITLE
macOS app crashing

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2411] opened 2018-03-19 05:39 UTC
/case/658914

osx_native_app/7.4.129

"Hello, Toggl continues to crash especially on the initial time I open it. I submitted before and cleared Kopsik folder as suggested. "

New log is available in case link.

**Comment by IndrekV** [comment] 2018-05-14 12:51
This issue was probably caused by some data handling issues. It should be fixed in the latest beta 7.4.155

**Comment by ricotheque** [comment] 2018-05-28 07:02
Thanks! 👍

**Comment by ricotheque** [comment] 2018-06-01 06:46
@IndrekV Unfortunately he's still encountering some problems 

/case/712387

**Comment by IndrekV** [comment] 2018-06-01 06:50
The new crash issue is different as it crashes when quitting the app. I created a new issue for it #2467

**Closed by IndrekV** 2018-06-01 06:50 UTC
Labels: bug, macOs
