### ISSUE TITLE
Linux desktop app crashes when disconnecting from 2nd monitor

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1809] opened 2016-01-29 10:18 UTC
Every time I disconnect my laptop from a second monitor, Toggl Desktop crashes. I'm running Toggl on Ubuntu 15.10.
linux_native_app/7.3.247
Reported with desk case #247230

**Comment by orschiro** [comment] 2016-02-04 06:03
Dear all, 

I can confirm this issue on Ubuntu 15.10. 

Steps to reproduce:

1. Launch Toogl Desktop while being connected to an external monitor.
2. Disconnect the external monitor.
3. Click on the tray indicator icon to start a new task.

At this stage, Toggl Desktop will crash.

**Comment by make** [comment] 2016-06-08 12:57
This occurs also on Ubuntu 14.04.

Sometimes the whole Ubuntu desktop and all open windows freeze so that only mouse cursor moves.
Only way to recover is to press Ctrl + Alt + F1 and ```sudo kill -9 <toggl process id>```

**Comment by IndrekV** [comment] 2016-07-15 12:15
duplicate of #1721

**Closed by IndrekV** 2016-07-15 12:15 UTC
Labels: linux
