### ISSUE TITLE
Menubar timer not in sync with the main timer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1027] opened 2014-12-29 12:56 UTC
timer in OS X topbar lags for 2-3 minutes
case 118904

**Comment by iBobik** [comment] 2015-01-07 14:51
Happens for me too.

**Comment by tanel** [comment] 2015-01-08 03:35
cannot reproduce in master branch

**Comment by tanel** [comment] 2015-01-09 12:39
the menubar timer does not render seconds. this could be a source of confusion, but it's by design.

I'm still not able to reproduce the issue in master branch, maybe its somehow user specific.

**Comment by tanel** [comment] 2015-01-09 13:16
The issue exists in the current released version, but is fixed in master, as noted above.

**Closed by tanel** 2015-01-09 13:16 UTC
Labels: bug, osx
