### ISSUE TITLE
Mac Desktop Not Syncing with Toggl Server

### ISSUE THREAD

**Issue by craigeley** [toggl/toggldesktop#1400] opened 2015-06-29 15:06 UTC
I have various scripts set up that interact with Toggl via the API, mostly from terminal. In the past, Toggl Desktop has reflected these changes nearly instantly, however, some recent update (I believe) seems to have affected how often Toggl Desktop "phones home" to sync with the server. Now, my command line changes are not reflected in the Desktop app until I manually sync. This is true with both starts and stops. The web interface, however, accurately reflects what's happening. Any idea what's going on?

**Comment by tanel** [comment] 2015-07-14 14:34
duplicate of #1400

**Closed by tanel** 2015-07-14 14:34 UTC
