### ISSUE TITLE
Autocomplete dropdown being overridding by entries underneath

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggldesktop#2526] opened 2018-07-25 05:34 UTC
When clicking on an entry from the autocomplete/suggestions dropdown it instead begins editing the time entry underneath, instead of populating the description and/or project.

User reported this and I have replicated this in the Windows app.

**Comment by IndrekV** [comment] 2018-07-25 06:50
duplicate of #2525

**Closed by IndrekV** 2018-07-25 06:50 UTC
Labels: windows

**Comment by ApocalypticFish** [comment] 2018-07-25 06:55
Sorry about that
