### ISSUE TITLE
Public projects issue with the Mac app

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggldesktop#3275] opened 2019-08-30 12:08 UTC
### 💻 Environment

Platform: macOS
OS Version: OS X 10.14.6
Toggl Version: 7.4.484
Case link: [🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/23463525139)

### 🐞 Actual behavior
Checking the box to make a project public while creating it along with a time entry doesn't work  - the project get created as a private project instead. 

### 💯 Expected behavior
If you choose to create a public project it should be created as one

### 🔨 Steps to reproduce

1. Start creating a time entry
2. Create a new project
3. Select to make it a public project
4. Check the outcome using the webapp

**Comment by skel35** [comment] 2019-08-30 12:17
Already fixed by #3254 (duplicate of #3236).

**Closed by skel35** 2019-08-30 12:17 UTC
