### ISSUE TITLE
Toggle desktop goes off sync with web version

### ISSUE THREAD

**Issue by dandaka** [toggl/toggldesktop#2708] opened 2018-12-17 10:37 UTC
### 💻 Environment

Platform: macOS
OS Version: 10.14.1 (18B75)
Toggl Version: 7.4.321

### 🐞 Actual behavior

Today I have ran Summary report to see work, that was done for last 1/2 month (from 1 to 15 December). I have seen, that time in report is significantly different from time in my desktop app (like 2x bigger tracked time in app). App was online.

I have checked Detailed report. I found that last week of work was not on web side, but is on my local app.

I have pressed Sync few times and restarted the desktop app. It took some time (like 30-60 seconds) to sync. Now desktop app and web app show similar results.

(Could not save the state, since it was needed to generate reports fast).

### 💯 Expected behavior

Desktop app is always in sync with web app. If there is some problem with syncing, user gets some errors / notifications.

### Things to note

I started to notice "Offline" status in Toggl desktop, when I started to use VPN software. VPN takes some time to connect / disconnect. After that process Toggl still thinks it is offline. And thinks so for whole session, until I restart the app.

I think those issues might be connected.

Doesn't seem like a proper bug report. But since there was a data loss, I think it deserves more investigation. I will report on this later.

**Comment by dandaka** [comment] 2018-12-18 07:08
![image](https://user-images.githubusercontent.com/2384694/50137617-5aa27880-02a4-11e9-9e9a-7dbab65f93ce.png)

This is how it looks in "false offline" mode. All other applications have access to internet without a problem. If I restart the Toggl app, it will get internet connection.

**Comment by IndrekV** [comment] 2018-12-19 11:16
This is fixed with the latest beta (7.4.330) that we just released. The issue was that when app lost connection to the network it would fail to reconnect and start syncing again. Thank you for pointing this issue out. 

Duplicate of #2685

**Closed by IndrekV** 2018-12-19 11:16 UTC
Labels: bug, macOs
