### ISSUE TITLE
Windows app unresponsive, appears to be stuck trying to connect to https server

### ISSUE THREAD

**Issue by dan-sorion** [toggl/toggldesktop#1444] opened 2015-08-04 10:21 UTC
Running on Windows 7 Pro 64-bit with all updates installed to date.

Since yesterday when Toggle updated itself to 7.2.219 the interface has been unresponsive. If the application loads and is only showing in the system tray there is no way to bring up the interface. I forced a reinstall and got the interface up with sign in, but then it hangs as soon as I've signed in. I've uninstalled it, deleted all the related files, reinstalled, same thing.

The log file shows an SSL3_GET_SERVER_CERTIFICATE error, over and over, eg:

	2015-08-04 10:12:59.757 [5948 5]:websocket_client:D:restarting
	2015-08-04 10:12:59.798 [5948 5]:websocket_client:D:createSession
	2015-08-04 10:12:59.831 [5948 5]:websocket_client:D:deleteSession
	2015-08-04 10:12:59.865 [5948 5]:websocket_client:D:session deleted
	2015-08-04 10:13:00.212 [5948 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-04 10:13:33.235 [5948 5]:websocket_client:D:restarting
	2015-08-04 10:13:33.273 [5948 5]:websocket_client:D:createSession
	2015-08-04 10:13:33.349 [5948 5]:websocket_client:D:deleteSession
	2015-08-04 10:13:33.434 [5948 5]:websocket_client:D:session deleted
	2015-08-04 10:13:33.830 [5948 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-04 10:14:07.899 [5948 5]:websocket_client:D:restarting

and repeat until process is killed.

At a guess it's in a blocking loop trying to connect to a server and this causes the interface to hang. I have no proxy running on my PC, so there should be no issue with an intermediate SSL proxy causing the remote certificate verification to fail.

If I start up Fiddler4 to see where the connection is being attempted so that I can attempt to check the server certificate I get an error about the port number being invalid, so that's a dead end too:

	2015-08-04 10:19:39.307 [5948 5]:websocket_client:D:restarting
	2015-08-04 10:19:39.390 [5948 5]:websocket_client:D:createSession
	2015-08-04 10:19:39.423 [5948 5]:websocket_client:D:deleteSession
	2015-08-04 10:19:39.448 [5948 5]:websocket_client:D:session deleted
	2015-08-04 10:19:39.525 [5948 5]:websocket_client:E:Syntax error: bad or invalid port number: 8888;https=127.0.0.1:8888
	2015-08-04 10:19:55.548 [5948 5]:websocket_client:D:restarting
	2015-08-04 10:19:55.657 [5948 5]:websocket_client:D:createSession
	2015-08-04 10:19:55.676 [5948 5]:websocket_client:D:deleteSession
	2015-08-04 10:19:55.701 [5948 5]:websocket_client:D:session deleted
	2015-08-04 10:19:55.758 [5948 5]:websocket_client:E:Syntax error: bad or invalid port number: 8888;https=127.0.0.1:8888

Dan

**Comment by killermouse0** [comment] 2015-08-04 11:36
+1. I feel less lonely ;)

Very same issue, as confirmed by the logs, since the application updated.
Windows 8.1 Enterprise edition

**Comment by amulware** [comment] 2015-08-04 11:43
Hey guys,

Thanks for reporting the problem!

We are currently investigating and hope that we will be able to find the problem soon.

**Comment by MagdalenaHent** [comment] 2015-08-05 17:20
Windows 8.1 here too, same problem as killermouse0.

**Comment by allan-s-laustsen** [comment] 2015-08-06 05:55
Same issue here, windows 7 - 64 bit

**Comment by tanel** [comment] 2015-08-06 09:03
Hi,

Users expecting the app freeze issue. Can you help us out and try to install this development build to see if the freezes are still there? Be sure to note your installed Desktop app version when giving us feedback.

Thank you!

**Comment by tanel** [comment] 2015-08-06 09:03
https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_233-2015-08-06-10-59-29.exe

**Comment by dan-sorion** [comment] 2015-08-06 09:46
Have installed it and so far looks good, it hasn't hung up and I can start and stop tasks. Still getting errors in the toggldesktop.log file for websocket_client though:

	2015-08-06 09:44:10.706 [5512 5]:websocket_client:D:restarting
	2015-08-06 09:44:10.737 [5512 5]:websocket_client:D:createSession
	2015-08-06 09:44:10.753 [5512 5]:websocket_client:D:deleteSession
	2015-08-06 09:44:10.780 [5512 5]:websocket_client:D:session deleted
	2015-08-06 09:44:11.078 [5512 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-06 09:44:22.222 [5512 5]:websocket_client:D:restarting
	2015-08-06 09:44:22.290 [5512 5]:websocket_client:D:createSession
	2015-08-06 09:44:22.319 [5512 5]:websocket_client:D:deleteSession
	2015-08-06 09:44:22.347 [5512 5]:websocket_client:D:session deleted
	2015-08-06 09:44:22.731 [5512 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed


Although there are other log entries interspersed with the posts to the Toggl server.

Thanks for getting this version out, I've missed Toggl and been using paper and pen to track my time spent on dev projects ... :|

Dan

**Comment by allan-s-laustsen** [comment] 2015-08-06 10:28
I have installed the new version, and so far no frezzes or hangs. Also it feels more responsive, compared to the earlier version.

Good work with a quick fix

**Comment by tanel** [comment] 2015-08-06 14:24
@dan-sorion it seems that on your location the websocket connection does not work for some reason. So it keeps attempting to restart the connection, ad infinitum. But its not blocking the UI so it should be fine.

**Comment by killermouse0** [comment] 2015-08-06 15:01
Installed the development build, tried the "About" screen to confirm version and it immediately froze. (Maybe an entirely different bug !)

**Comment by tanel** [comment] 2015-08-06 15:43
Does it happen each time?

**Comment by dan-sorion** [comment] 2015-08-06 15:51
I've tried the About box, first time I closed it the Toggl gui was sluggish and took a few seconds to start responding properly again. Tried it a few more times, doesn't seem to cause an issue although might be a little sluggish for a half second or so.

**Comment by dacohenii** [comment] 2015-08-06 16:17
I've been experiencing this issue (app unresponsive) in the latest stable release (7.2.219) on Win7 64-bit. 

Just installed the build you posted (7.2.233) and so far it appears to be resolved. Thank you!

**Comment by tanel** [comment] 2015-08-06 17:14
Thanks @dacohenii @dan-sorion for the feedback!!

It looks like the About window sluggishness is another issue. Perhaps its checking for updates and locking while doing so. I've created another issue regarding this.

**Comment by tanel** [comment] 2015-08-06 17:16
btw please write to support@toggl.com to receive nice Toggl swag, if you'd like to. Just mention Desktop app testing.

**Comment by dan-sorion** [comment] 2015-08-07 07:11
Just had another hang, this time as I stopped a running task, entered a new task name, and clicked the Start button. Now the interface is hung with it looking like it hasn't started the new task, and the mouse disappears when I move it over the interface. Can't click anything, systray icon does nothing either. Here's the last extract from the log (websocket issues removed for clarity, id strings removed just in case it's related to my account)

2015-08-07 06:45:17.946 [6180 1]:BatchUpdateResult:D:[{"method":"PUT","guid":"<guid>","body":"{\"data\":{\"id\":<id>,\"guid\":\"<guid>\",\"wid\":<wid>,\"billable\":false,\"start\":\"2015-08-07T06:30:39Z\",\"stop\":\"2015-08-07T06:45:14Z\",\"duration\":875,\"description\":\"check archive and deletion job\",\"duronly\":false,\"at\":\"2015-08-07T06:45:17+00:00\",\"ui_modified_at\":\"1438929914\",\"uid\":<uid>}}","status":200,"content_type":"application/json; charset=utf-8"}]
2015-08-07 06:45:17.983 [6180 0]:ui:D:DisplayTimeEntryAutocomplete
2015-08-07 06:45:18.013 [6180 1]:BatchUpdateResult:D:batch update result GUID: <guid>, StatusCode: 200, ContentType: application/json; charset=utf-8, Body: {"data":{"id":<id>,"guid":"<guid>","wid":<wid>,"billable":false,"start":"2015-08-07T06:30:39Z","stop":"2015-08-07T06:45:14Z","duration":875,"description":"check archive and deletion job","duronly":false,"at":"2015-08-07T06:45:17+00:00","ui_modified_at":"1438929914","uid":<uid>}}
2015-08-07 06:45:18.068 [6180 1]:ui:D:DisplayOnlineState online
2015-08-07 06:45:18.069 [6180 0]:ui:D:DisplayMinitimerAutocomplete
2015-08-07 06:45:18.143 [6180 0]:ui:D:DisplayTimerState
2015-08-07 06:45:18.176 [6180 1]:database:D:Updating time entry TimeEntry ID=<id> local_id=35 description=check archive and deletion job wid=<wid> guid=<guid> pid=0 tid=0 start=1438929039 stop=1438929914 duration=875 billable=0 duronly=0 tags= created_with=windows_native_app/7.2.233 ui_modified_at=0 deleted_at=0 updated_at=1438929917 in thread 7176
2015-08-07 06:45:18.302 [6180 1]:database:D:User with_related_data=1 saved in 126 ms in thread 7176
2015-08-07 06:45:18.334 [6180 1]:ui:D:DisplayTimeEntryList open=0, has items=36
2015-08-07 06:46:04.544 [6180 4]:timeline_uploader:D:upload_loop_activity (current interval 480s)

(followed by lots of websocket errors which I've now determined to be due to the firewall configuration where I am located)

I've now killed the TogglDesktop process and run it again, and it shows the task I'd click Start on as running and has the correct start time and duration. Stopped that task, click the > button to restart it, so far so good. Stopped that, wrote in a new task, clicked Start, again ok. It was working ok all day yesterday after installing the latest build, although I only stopped and started tasks a couple of times.

I've gone back through the log a little and found the following log entries which would explain the uploader interval:

2015-08-07 06:31:00.090 [6180 5]:websocket_client:E:Timeout
2015-08-07 06:31:01.894 [6180 1]:database:D:User with_related_data=1 saved in 0 ms in thread 7176
2015-08-07 06:31:21.273 [6180 4]:ServerStatus:D:UpdateStatus status_code=0
2015-08-07 06:31:21.350 [6180 4]:timeline_uploader:W:backoff
2015-08-07 06:31:21.380 [6180 4]:timeline_uploader:D:Upload interval set to 120s
2015-08-07 06:31:21.405 [6180 4]:timeline_uploader:E:Timeout

2015-08-07 06:33:21.451 [6180 4]:timeline_uploader:D:upload_loop_activity (current interval 120s)
2015-08-07 06:33:21.481 [6180 4]:user:D:CompressTimeline  user_id=<userid> chunk_up_to=1438929000 number of events=274
2015-08-07 06:33:21.506 [6180 4]:user:D:CompressTimeline done in 0 seconds, 274 compressed into 0 chunks
2015-08-07 06:33:21.548 [6180 4]:database:D:User with_related_data=1 saved in 0 ms in thread 7864
2015-08-07 06:33:21.573 [6180 4]:timeline_uploader:D:Uploading 7 event(s) of user <userid>
2015-08-07 06:33:21.604 [6180 4]:timeline_uploader:D:[
      <list of running applications ....>
]

2015-08-07 06:33:21.668 [6180 4]:TogglClient:D:Sending request to https://timeline.toggl.com/api/v8/timeline ..
2015-08-07 06:33:23.574 [6180 1]:database:D:User with_related_data=1 saved in 0 ms in thread 7176
2015-08-07 06:33:42.743 [6180 4]:ServerStatus:D:UpdateStatus status_code=0
2015-08-07 06:33:42.916 [6180 4]:timeline_uploader:W:backoff
2015-08-07 06:33:42.941 [6180 4]:timeline_uploader:D:Upload interval set to 240s
2015-08-07 06:33:42.971 [6180 4]:timeline_uploader:E:Timeout

2015-08-07 06:36:08.994 [6180 1]:TogglClient:D:Sending request to https://www.toggl.com/api/v8/me?app_name=windows_native_app&with_related_data=true&since=1438878753 ..
2015-08-07 06:36:30.312 [6180 1]:ServerStatus:D:UpdateStatus status_code=0
2015-08-07 06:36:30.397 [6180 1]:ui:E:Timeout
2015-08-07 06:36:30.423 [6180 1]:ui:D:DisplayOnlineState no network
2015-08-07 06:37:42.997 [6180 4]:timeline_uploader:D:upload_loop_activity (current interval 240s)
2015-08-07 06:37:43.077 [6180 4]:user:D:CompressTimeline  user_id=<userid> chunk_up_to=1438929000 number of events=274
2015-08-07 06:37:43.113 [6180 4]:user:D:CompressTimeline done in 0 seconds, 274 compressed into 0 chunks
2015-08-07 06:37:43.144 [6180 4]:database:D:User with_related_data=1 saved in 0 ms in thread 7864
2015-08-07 06:37:43.180 [6180 4]:timeline_uploader:D:Uploading 7 event(s) of user <userid>
2015-08-07 06:37:43.215 [6180 4]:timeline_uploader:D:[
   <list of running processes ...>
]
2015-08-07 06:37:43.282 [6180 4]:TogglClient:D:Sending request to https://timeline.toggl.com/api/v8/timeline ..
2015-08-07 06:37:45.181 [6180 1]:database:D:User with_related_data=1 saved in 0 ms in thread 7176
2015-08-07 06:38:04.338 [6180 4]:ServerStatus:D:UpdateStatus status_code=0
2015-08-07 06:38:04.423 [6180 4]:timeline_uploader:W:backoff
2015-08-07 06:38:04.459 [6180 4]:timeline_uploader:D:Upload interval set to 480s
2015-08-07 06:38:04.489 [6180 4]:timeline_uploader:E:Timeout

At no point did the UI display a message saying that the server was offline (at this point in time I was connected to a VPN with no outgoing internet access, so the lack of internet connection was expected). It was however responsive, and was responsive when I disconnected from the VPN. It was only when I stopped the running task and started a new one did it hang.

What's also a little concerning going through the logs is how much data is sent to the Toggl servers regarding the applications I have running on my laptop. Does it really need to know this information?

**Comment by tanel** [comment] 2015-08-07 10:48
@dan-sorion what version of the app are you using?

you can disable timeline recording; then no data will be sent to Toggl server.

**Comment by killermouse0** [comment] 2015-08-07 12:29
Hello,

Unfortunately the issue is still here with v7.2.233.
Windows 8.1 Enterprise 64bits.

Stopped a task and the UI froze. Here's the log : 

	2015-08-07 12:23:50.771 [8880 0]:toggl_api:D:toggl_stop
	2015-08-07 12:23:50.777 [8880 1]:ui:D:DisplayTimeEntryEditor
	2015-08-07 12:23:55.259 [8880 5]:websocket_client:D:restarting
	2015-08-07 12:23:55.264 [8880 5]:websocket_client:D:createSession
	2015-08-07 12:23:55.267 [8880 5]:websocket_client:D:deleteSession
	2015-08-07 12:23:55.273 [8880 5]:websocket_client:D:session deleted
	2015-08-07 12:23:55.539 [8880 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-07 12:24:26.556 [8880 5]:websocket_client:D:restarting
	2015-08-07 12:24:26.560 [8880 5]:websocket_client:D:createSession
	2015-08-07 12:24:26.562 [8880 5]:websocket_client:D:deleteSession
	2015-08-07 12:24:26.564 [8880 5]:websocket_client:D:session deleted
	2015-08-07 12:24:26.825 [8880 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-07 12:24:47.801 [8880 4]:timeline_uploader:D:upload_loop_activity (current interval 60s)
	2015-08-07 12:24:47.835 [8880 5]:websocket_client:D:restarting
	2015-08-07 12:24:47.838 [8880 5]:websocket_client:D:createSession
	2015-08-07 12:24:47.840 [8880 5]:websocket_client:D:deleteSession
	2015-08-07 12:24:47.843 [8880 5]:websocket_client:D:session deleted
	2015-08-07 12:24:48.098 [8880 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	2015-08-07 12:25:10.123 [8880 5]:websocket_client:D:restarting
	2015-08-07 12:25:10.127 [8880 5]:websocket_client:D:createSession
	2015-08-07 12:25:10.130 [8880 5]:websocket_client:D:deleteSession
	2015-08-07 12:25:10.132 [8880 5]:websocket_client:D:session deleted
	2015-08-07 12:25:10.391 [8880 5]:websocket_client:E:SSL Exception: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by dan-sorion** [comment] 2015-08-07 12:32
@tanel I'm using 7.2.233.

I've disabled timeline recording, I thought I'd already done that before but obviously not.

I won't be able to do any more testing for a couple of weeks as it's now vacation time :)

**Comment by anagami** [comment] 2015-08-09 07:38
Hi!
Still not working. After install TogglDesktopInstaller-7_2_233-2015-08-06-10-59-29.exe. When run toggle - in system tray in beginner grey icon, after few second - red. double click or click for context menu not working. Win 8.1 64bit

How i can trun off autoupdate? I have TogglDesktopInstaller-7_2_36 installer , wich stable working on my machine. But after few time, toggl updatet to last version. And i can't use tracker

**Comment by xairrick** [comment] 2015-08-10 12:17
7_2_219-2015-07-28-18-07-06  would start but then hang when the UI was displayed (I trying clearing clearing cache & re-installing) Windows 8.1 PRO 64bit

7_2_233-2015-08-06-10-59-29  is working on my system.

**Comment by xairrick** [comment] 2015-08-11 10:30
7_2_233-2015-08-06-10-59-29 is working.  But the Project dropdown isn't showing any of my projects.  I tried clearing the cache and logged back in, but when I did this the app froze.  Manually killing the app and restarting allow the app to work, but projects are still missing.

Here is what the logs look like when it hangs;

```
2015-08-11 10:23:26.402 [3364 8]:database:D:Inserting time entry TimeEntry ID=260480418 local_id=0 description=Ribbon Customization wid=727029 guid=db071883-aa97-405e-8399-0696462da503 pid=10422670 tid=0 start=1439235666 stop=1439239196 duration=3530 billable=0 duronly=0 tags= created_with= ui_modified_at=0 deleted_at=0 updated_at=1439239199 in thread 2024
2015-08-11 10:23:26.412 [3364 8]:database:D:User with_related_data=1 saved in 401 ms in thread 2024
2015-08-11 10:23:26.418 [3364 8]:ui:D:DisplayTimeEntryList open=0, has items=50
2015-08-11 10:23:27.948 [3364 1]:TogglClient:D:Sending request to https://www.toggl.com/api/v8/updates?app=td&channel=beta&platform=windows&version=7.2.233&osname=Windows NT&osversion=6.2 (Build 9200)&osarch=IA32 ..
2015-08-11 10:23:28.085 [3364 1]:TogglClient:D:GET /api/v8/updates?app=td&channel=beta&platform=windows&version=7.2.233&osname=Windows%20NT&osversion=6.2%20(Build%209200)&osarch=IA32 HTTP/1.1
Connection: Close
User-Agent: windows_native_app/7.2.233
Transfer-Encoding: chunked
Content-Encoding: gzip
Host: www.toggl.com
Accept-Encoding: gzip


2015-08-11 10:23:28.090 [3364 1]:TogglClient:D:Request sent. Receiving response..
2015-08-11 10:23:28.134 [3364 1]:TogglClient:D:Response status code 200, content length 4, content type application/json; charset=utf-8, unknown content encoding
2015-08-11 10:23:28.139 [3364 1]:TogglClient:D:X-Toggl-Request-Id bd79c43f-2d65-45f2-6c05-d649c0ad8749
2015-08-11 10:23:28.143 [3364 1]:ServerStatus:D:UpdateStatus status_code=200
```

**Comment by amulware** [comment] 2015-08-11 12:06
We are aware of the issue with the project dropdown, and are investigating.

Thanks for your help and patience, everybody!

**Comment by tombeardhid** [comment] 2015-08-12 06:36
I'm having the same issue.  For what it's worth, I suspect my corporate antivirus, Kaspersky Endpoint Security 10, blocking partial network communication with the app.  Nothing to support this other than a hunch.  Anyone else using antivirus with built-in firewall, especially Kaspersky?  I'm on a Win 7 64-bit machine and can reproduce it on two different machines.

**Comment by IndrekV** [comment] 2015-08-12 06:46
@tombeardhid We have had reports from users who have had issues with Kaspersky blocking the app. The users have contacted Kaspersky and have gotten solution from their support.

**Comment by amulware** [comment] 2015-08-12 07:07
Hey guys!

We got a new build that is holding up pretty well in our own tests:
https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_261-2015-08-11-23-59-06.exe

Hopefully, the freezing/crashing is gone for good, and the projects should be back as well.

It would be great if you could give it a try and let us know how it is working for you.

**Comment by killermouse0** [comment] 2015-08-12 09:38
@amulware Installing it right now. Fingers crossed !
I'll report back by the end of the day.

Thanks for your efforts !

**Comment by amulware** [comment] 2015-08-12 11:53
Just so you guys know: There are some issues with the edit window not always updating correctly when editing right now. We know what causes this and are already on it.

**Comment by xairrick** [comment] 2015-08-12 12:04
installed 7_2_261-2015-08-11-23-59-06.  no hangs, project dropdown is working.

**Comment by tanel** [comment] 2015-08-12 15:23
the issue is fixed now; we're pushing to beta. thanks to everybody for the patience and feedback.

**Closed by tanel** 2015-08-12 15:23 UTC
Labels: bug, windows
