### ISSUE TITLE
Can't log into app on macOS

### ISSUE THREAD

**Issue by jakepetroules** [toggl/toggldesktop#2309] opened 2017-10-26 19:41 UTC
<img width="536" alt="screen shot 2017-10-26 at 12 40 29 pm" src="https://user-images.githubusercontent.com/1312511/32073435-e2d52b74-ba4a-11e7-971f-1b4f4ee3841d.png">

The screenshot should say it all. This is on macOS 10.13, and it should be considered a critical issue since login is now impossible.

Version 7.4.58

**Comment by IndrekV** [comment] 2017-10-26 21:50
duplicate of #2292 

Issue has already been fixed. Just reinstall the latest [MacOs stable](https://toggl.com/api/v8/installer?app=td&platform=darwin&channel=stable)

**Closed by IndrekV** 2017-10-26 21:50 UTC
Labels: bug, macOs

**Comment by jakepetroules** [comment] 2017-10-27 02:26
The latest stable release *IS* the affected version - 7.4.58. I had to install a pre-release version to get the issue fixed.

Please update what's actually marked as the stable release, as there seems to be a disconnect here.
