### ISSUE TITLE
Timeline problems 

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2139] opened 2017-03-08 05:06 UTC
case/438493

"Timeline is not working. My IT department and I have been in touch about getting this to work again on my PC. We've added all options to firewalls and I have un-installed and re-installed. Recent request was to send logs. I hope this helps. I can only see active and inactive times and do not get any data about the applications I'm running or websites I visit anymore. Thanks"

logs included in case
request for screenshot in case as well

**Comment by kadrihvl** [comment] 2017-03-08 10:31
We were able to replicate. Also reported by other users. Nothing seems to fix this, tried logout / login; fiddling with timeline recording setting in h4x.

**Comment by nicktoggl** [comment] 2017-03-08 23:49
https://toggl.slack.com/archives/inbox-0/p1489008890367182 appears to be a display issue rather than a timeline problem, Andrin says fixed

**Comment by zdericnina** [comment] 2017-06-05 08:26
User is still having issues with Timeline but with the fact that the Timeline is only tracking two programs and not others:

> The only applications that show up are RingCentralMeetings.exe and Acrobat.exe.
> Applications that do not show up are all website visits - I use Chrome and Explorer, and all programs including Outlook, Word, Excel, Photoshop, etc.

It is said that this issue appears in Win 7 most often, however, the user is using Windows 8.1 Pro so it might affect more OS.

Case #438493

**Comment by odeland** [comment] 2017-06-09 14:05
Might be related to https://github.com/toggl/toggldesktop/issues/1861
Chrome stopped getting recorded for me a couple weeks ago. All I see is notepad++ and some other programs, but Chrome and PHPStorm are just blank entries. I send feedback from the app, hopefully we can get to the bottom of this. I'm also using Window 8.1.

Could it be an issue with 32bit vs 64bits application? It seems to only record 32bits application for me, and I think Chrome went 64 bit native a few weeks ago. In fact I'm positive this is probably the issue here.

**Comment by odeland** [comment] 2017-06-30 12:54
I looked into the code a bit, I haven't touched C++ in over 15 years, but a little of googling led me to this problem and answer which I believe is the issue we have here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/58f6cbfe-8bde-4051-9849-42a98a88b978/issue-with-class-process-class-in-64bit?forum=netfxbcl

Basically, the problem is that OpenProcess will fail if we are compiled as x86 and we're trying to open a 64 bit process:
https://github.com/toggl/toggldesktop/blob/master/src/get_focused_window_windows.cc#L49

I'm not confident enough in C++ to write a patch, but hopefully someone can implement the solution described on the microsoft forums.

**Comment by IndrekV** [comment] 2017-07-01 13:02
@odeland You're on to something here. We'll test the app with 32bit and 63bit applications to see if the issue is with tracking 64bit. Thank you for pointing this out.

**Comment by vedr4n** [comment] 2017-10-26 06:32
I've got another user saying they are experiencing problems with Timeline on Windows 7. It's not tracking Firefox. 

Case 574042

**Comment by konstantinosftw** [comment] 2018-06-17 12:13
I have win 10/64 bit. Autotracker and Timeline stopped tracking Chrome pages since the 13th of June. It could be that my OS or Chrome got some updates then, because It was working properly before that.

**Comment by IndrekV** [comment] 2019-07-11 03:44
Will be fixed with 64bit release.

**Closed by IndrekV** 2019-07-11 03:44 UTC
Labels: bug
