### ISSUE TITLE
Menubar timer text is not in line with mac clock

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1901] opened 2016-05-09 08:24 UTC
The text is 1 pixel lower than the clock.
![image](https://cloud.githubusercontent.com/assets/842229/15107412/5c03ff70-15d8-11e6-9804-1448060ea178.png)

This might be built in and not editable.

**Comment by Leland** [comment] 2018-02-01 18:20
Looks to be dupe of (closed) issue #1749

**Closed** 2018-02-01 20:20 UTC
Labels: macOs
