### ISSUE TITLE
Sometimes Ctrl+C is not working in description textbox

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1464] opened 2015-08-13 13:13 UTC
User reports this on version 7.2.219
Case 181155

**Comment by amulware** [comment] 2015-08-13 13:53
This is handled by the framework and _should_ not happen. Did a few tests and cannot reproduce it either. May need more info/testing.

**Comment by amulware** [comment] 2015-08-17 10:00
Closing until we can reproduce.

**Closed by amulware** 2015-08-17 10:00 UTC
Labels: bug, windows
