### ISSUE TITLE
Windows Desktop app often locks up

### ISSUE THREAD

**Issue by GLMeece** [toggl/toggldesktop#1483] opened 2015-08-17 15:51 UTC
This latest version ("stable" channel - v. 7.2.281) seems to lock up quite a bit. Most noticed upon starting the timer, and then attempting to adjust the start time. The entire UI locks up, and even if you "give it time" to settle down, the Windows Task Manager shows it not responding in perpetuity.

I'll try to create some consistent, repeatable test cases. Additionally, if any of the devs want to give me direction on how you want me to get log or debug information, that would be great.

**Comment by iatsyk** [comment] 2015-08-18 08:29
For me it often freezing up while I trying to edit something (like time entry or project). After that I can't do anything with it and just stop it through task manager. And it happens one or two time per day, I mean - very often.

**Comment by amulware** [comment] 2015-08-18 10:47
Thanks for letting us know of the problem.

Could you send us a support ticket from inside the program ("Send feedback" in the menu)? That will automatically include the log files, which might give us some clues as to what is going on.
Please add in the message that it is for me (Paul) so that the support team knows what to do with it!

And of course, if you can find some way of reliably reproduce the freeze, that would be helpful.

@iatsyk Can you make sure that you have the latest build installed? You can check the version number in the about window. (should be 7.2.281)

Sorry about the inconvenience, and thanks for your help!

**Comment by iatsyk** [comment] 2015-08-18 11:11
@amulware yes, I have version 7.2.281, and this freeze start appear after installing this version
and yes, next time I see the problem I will "Send feedback" to you.

**Comment by GLMeece** [comment] 2015-08-18 15:01
@amulware - yes, I'll do the same. I would echo the comments of @iatsyk as that what I observe as well. I would mention, however, that once the app locks up, nothing in the UI responds, so I'm not sure how I can "Send Feedback" from the menu when the menus don't respond. :anguished:

**Comment by amulware** [comment] 2015-08-18 15:05
No worries! You can just use 'send feedback' after restarting the program. The log files are not cleared when exiting/starting. If there is something useful in the file, we'll find it. :)

**Comment by GLMeece** [comment] 2015-08-18 15:08
@amulware - awesome, will do. :+1:

**Comment by amulware** [comment] 2015-08-19 11:55
@GLMeece @iatsyk 
We have been investigating, and while we have some ideas of what might be going on, we still are not sure why some users have the problem while others do not.

We are working on getting a new version with some detailed performance measurements out, so that we can do some actual tests to see what parts of the program are the problem.

In the mean time we are still looking for what the people with this issue have in common.

Could you guys let me know what hardware and operating system you are running Toggl Desktop on (CPU, GPU, Ram)?

**Comment by iatsyk** [comment] 2015-08-19 12:09
@amulware 
http://prntscr.com/86eop8

**Comment by amulware** [comment] 2015-08-21 09:04
Thanks for the screenshot!

We have another lead on the cause of the problem: It might be related to something going wrong with the installation of the update.

Could you try to completely delete Toggl Desktop and all its data (Delete everything in C:\Users\<username>\AppData\Local\TogglDesktop) and then re-installing with [the latest installer](https://toggl.com/api/v8/installer?app=td&platform=windows&channel=stable)?

This has worked for at least one user so far.

**Comment by iatsyk** [comment] 2015-08-21 09:45
done
in case the problem appears again I will report to you

**Comment by anagami** [comment] 2015-09-07 08:05
Hello!
one week ago send feedback trouth TogglDesktop about same problem
today i have reduce speed internet and now desktop app start freezing more times

**Comment by amulware** [comment] 2015-09-07 09:06
Hey everyone,

We just released a new beta build that we hope will improve performance. You can get the installer here:
https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_313-2015-09-03-20-37-50.exe

Before you install it, I suggest you (again) manually clean the Toggl Desktop install directory at C:\Users<username>\AppData\Local\TogglDesktop, just in case.

If you still have problems with that build, please report it through the in-app feedback function. That will automatically attach the log files, which - since this build - include a lot of performance measurements, which we hope we can use to further improve performance, if needed.

Thanks a lot for your patience and help!

**Comment by anagami** [comment] 2015-09-07 10:16
@amulware
Thanks! Now looking better and no freezing

**Comment by flap152** [comment] 2015-09-15 18:25
I had the same problem and the beta version mentionned above fixed it.

**Comment by amulware** [comment] 2015-09-15 18:29
Great to hear, thanks for letting us know! We will probably release the beta to stable next week, so that everyone can benefit from the improvements.

Since it seems that things are resolved with the new version, I'll close this issue.
Thanks again everybody for helping out with your feedback!

**Closed by amulware** 2015-09-15 18:29 UTC
Labels: windows
