### ISSUE TITLE
Linux desktop app crashes

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2584] opened 2018-10-04 09:07 UTC
Linux 7.4.184 Beta

When I click on 'Add new project' - 'Add new client' - Fill new client name - click on 'Add' button ToggleDesktop crashed

More information on bug, with video and log log at conversations/18549944315

**Comment by MartinBriza** [comment] 2018-11-22 19:45
I can't reproduce this. Is there anything specific that triggers this?

**Comment by IndrekV** [comment] 2018-12-06 10:07
Unable to reproduce this. Closing.

**Closed by IndrekV** 2018-12-06 10:07 UTC
Labels: bug, linux
