### ISSUE TITLE
Show Project and Tags Icon for current task

### ISSUE THREAD

**Issue by Richtor** [toggl/toggldesktop#1156] opened 2015-02-19 22:58 UTC
It would be very helpful if the task color (any maybe font color too) were shown for the currently running task.  Also, it would be great to see if there are tags and if item was billable.
![image](https://cloud.githubusercontent.com/assets/5933687/6277893/aa9e45a6-b84f-11e4-89f4-227e5ce57488.png)

**Comment by IndrekV** [comment] 2015-06-16 07:54
This is already in development
Duplicate of #1366

Thank you for your feedback.

**Closed by IndrekV** 2015-06-16 07:54 UTC
