### ISSUE TITLE
Position not saved on close

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggldesktop#2149] opened 2017-03-23 07:48 UTC
User claiming that the app isn't remembering its position after closing and restarting the app on Ubuntu 16.10 with Gnome 3.20. The app isn't being force closed, it's closed from within the app. 

Don't have access to a Linux machine. Can't reproduce on Windows or MacOS. 

---
Desk case: 440162

**Comment by IndrekV** [comment] 2017-03-23 18:10
Confirmed. There is currently no position and window size saving in Linux.

**Comment by sojusnik** [comment] 2017-03-29 20:57
Same here.
I'm using an external monitor with a notebook, if that helps.

**Comment by IndrekV** [comment] 2017-12-14 23:42
duplicate of #1644

**Closed by IndrekV** 2017-12-14 23:42 UTC
Labels: linux
