### ISSUE TITLE
Auto-complete won't let me enter a new time entry.  

### ISSUE THREAD

**Issue by Catmacey** [toggl/toggldesktop#2477] opened 2018-06-07 08:42 UTC
Currently the app is unusable as the autocomplete won't let me enter a new time entry if it matches in any way with a previously existing time entry.

Eg. 
Assuming I already have the following time entries;
-  "Project A"
-  "Project B"

I want to add a new time entry called "Project C" 
I can type that in but when I hit return the autocomplete will pick "Project A" replacing what I typed in.

If I enter "XYZ" then the autocomplete doesn't match any existing entry so allows me to create a new one with this title.

Windows 10.
Toggle Desktop: 7.4.176

**Comment by IndrekV** [comment] 2018-06-07 09:36
Thank you for the detailed description. This issue is a duplicate of #2473 
This is already fixed and if all goes well will released some time today.

**Closed by IndrekV** 2018-06-07 09:36 UTC
Labels: windows
