### ISSUE TITLE
Bug report: Toggl Desktop crashes when starting timer

### ISSUE THREAD

**Issue by thestick366** [toggl/toggldesktop#1319] opened 2015-04-29 13:34 UTC
See title. When I try to start the timer, the computer freezes, then Toggl crashes.

The timer does indeed start, since I can see the entry running on the web version.

I am running Windows 8.1.

**Comment by tanel** [comment] 2015-05-13 15:30
duplicate of #1139

**Closed by tanel** 2015-05-13 15:30 UTC
