### ISSUE TITLE
Completed tasks showing in autocomplete

### ISSUE THREAD

**Issue by timgaunt** [toggl/toggldesktop#1060] opened 2015-01-13 15:48 UTC
We've got a couple of completed tasks which are still showing in the auto-complete drop down list. This list should be refreshed on load of the app (or at least daily). Some of the tasks were completed a long time ago.

**Comment by tanel** [comment] 2015-01-14 06:35
Cannot reproduce the issue. Please check that you have latest app version, if you do, please contact support@toggl.com and tell us the exact task name(s) that are marked as done but still show up.

**Closed by tanel** 2015-01-14 06:35 UTC
Labels: bug, lib
