### ISSUE TITLE
Better support for retina displays

### ISSUE THREAD

**Issue by scrobbleme** [toggl/toggldesktop#1389] opened 2015-06-26 06:34 UTC
See screenshots for latest version from homepage (7_2_172-2015-06-11-16-22-57).
This already worked in a previous version.

![toggl_retina](https://cloud.githubusercontent.com/assets/504835/8371899/0ddd11dc-1bde-11e5-860a-6f5b9cb77eb5.jpg)

My environment: Dell XPS 17 with Windows 8.1

**Comment by amulware** [comment] 2015-06-26 07:32
Thanks for reporting the problem!

This is a known issue with the latest version.
We are not yet sure what is going on, but are investigating it and are hoping to be able to fix it soon.

For now, it may help somewhat if you disable display-scaling for TogglDesktop. See here:
http://ccm.net/faq/32589-windows-8-1-disable-display-scaling-on-high-dpi-settings

(closed as duplicate of #1379)

**Closed by amulware** 2015-06-26 07:32 UTC

**Comment by scrobbleme** [comment] 2015-06-26 07:39
Awesome, thanks. this works for me. Wasn't aware this feature.
