### ISSUE TITLE
window disappearing

### ISSUE THREAD

**Issue by witekp** [toggl/toggldesktop#1395] opened 2015-06-26 20:33 UTC
It has been for a week dissappering partially like that. What happend?
![image](https://cloud.githubusercontent.com/assets/13070024/8386788/e5080fd0-1c07-11e5-889c-d344dd6e3147.png)

**Comment by tanel** [comment] 2015-06-26 20:46
assuming its the windows app, it's a known issue: https://github.com/toggl/toggldesktop/issues/1375

we're working on it. we're sorry about the inconvenience.

i'll close this issue as a duplicate of #1375

**Closed by tanel** 2015-06-26 20:46 UTC
