### ISSUE TITLE
Windows 7.4.184 sometimes crashing when choosing a project

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggldesktop#2495] opened 2018-06-18 08:46 UTC
User reported that the Windows app (7.4.184) sometimes crashes when choosing a project. 

> After last update. It keeps crashing when i try to choose project. Hangs for a few secs, and then closes down completly. No errors shown or nothing.

case/723669 - logs included

**Comment by maritoggl** [comment] 2018-07-12 07:42
conversation/17441911664 referring to the same problem. Logs included.

**Comment by TheSoloJake** [comment] 2018-07-12 20:20
User from @maritoggl conversation has responded with further steps on how they recreate the bug

**Comment by IndrekV** [comment] 2018-07-13 04:03
Probably duplicate of #2486 
Ask the user to try latest beta.

**Closed** 2018-07-20 21:22 UTC
Labels: windows
