### ISSUE TITLE
App window "disappears" when "On top of other windows" is selected

### ISSUE THREAD

**Issue by ckdot** [toggl/toggldesktop#1932] opened 2016-06-21 10:48 UTC
This is a copy of the closed issue from 2014:
https://github.com/toggl/toggldesktop/issues/911
- Check "On top of other windows" in preferences
- Click on the Toggl icon in the dock to open the app window
- Minimize the app window by clicking on the yellow minimize button (not the red one for closing)

Please see screen recording
[toggl_bug.zip](https://github.com/toggl/toggldesktop/files/325363/toggl_bug.zip)

**Comment by IndrekV** [comment] 2016-06-21 11:01
Hi I'm still not able to reproduce this. Maybe it has something to do with the dock preferences. Could you please let me know what preferences have you enabled for dock.

Also it might be issue with the speed you are closing and showing the app. Does the same happen when you wait a few seconds after hiding the app.

**Comment by ckdot** [comment] 2016-06-21 11:18
Hey, the time between closing and showing the app doesn't matter. If I click the minimize button, the problem will always occur.
Dock preferences are attached.

Btw.: I'm not the person who posted this issue 2 years ago. So it seems to happen on several Macs.
<img width="679" alt="screen shot 2016-06-21 at 13 17 49" src="https://cloud.githubusercontent.com/assets/7283097/16227711/a0c181d6-37b2-11e6-927c-d645f598a2b4.png">

**Comment by IndrekV** [comment] 2016-06-21 11:21
Bingo! If `Minimize windows into application icon` is enabled this bug happens. Thank you for sending the details.

**Comment by ckdot** [comment] 2017-07-11 12:47
Looks like that issue is fixed, can't reproduce anymore.

**Closed** 2017-07-12 19:18 UTC
Labels: bug, macOs
