### ISSUE TITLE
Annoying timer overlay on top of all

### ISSUE THREAD

**Issue by scrobbleme** [toggl/toggldesktop#1755] opened 2015-12-19 11:26 UTC
Since today I have a timer overlay at the top left, which I can't move or disable (didn't found anything within the settngs). 

![2015-12-19 12_23_10-](https://cloud.githubusercontent.com/assets/504835/11912754/9ecc8d56-a64b-11e5-876d-d35bc3dedec3.png)

**Comment by IndrekV** [comment] 2015-12-20 08:02
It is not by design. Does this come back when you restart the app?

**Comment by scrobbleme** [comment] 2015-12-20 10:17
Yes, this is permanent, even after a restart. I also have this issue on two different PC's.

* Windows 10
* Toggle version: 7.3.199

I noticed that logging out from the app and logging in again "solved" this (at least on one the devices).

**Comment by amulware** [comment] 2015-12-21 10:02
This looks like the hover-tooltip of the notification icon on the taskbar.

@scrobbleme:
If the little box visible, does anything happen if you hover on the Toggl Desktop icon (in the notification area / systray) for a few seconds?

**Comment by scrobbleme** [comment] 2015-12-21 10:17
@amulware No, nothing. The box doesn't seem to be there for the mouse. When I hover or click the event is propaged to the app behind the box.

**Comment by amulware** [comment] 2015-12-22 13:50
So far I have not been able to reproduce this. It seems like it only happens under specific circumstances.

**Comment by amulware** [comment] 2015-12-23 11:13
Closing this until we get more information that helps us reproduce it.

**Closed by amulware** 2015-12-23 11:13 UTC
Labels: bug, windows

**Comment by Voyz** [comment] 2016-12-12 15:16
The bug is still present, though not sure how to reproduce it

**Comment by linnflux** [comment] 2017-03-17 16:11
I encountered this bug randomly after using Toggl Desktop for a few months.  I found this thread.  Clicking on the Toggl logo in the sys tray fixed it for me.  Windows 10.

**Comment by macbikegeek** [comment] 2017-03-27 15:10
thanks, @linnflux. It suddenly showed up for me this morning after using Toggl Desktop for a couple years. Your method fixed it for me, too. Also on Windows 10.

**Comment by luke-du-hast** [comment] 2019-08-16 15:14
Thanks @linnflux. I can also confirm your fix works for my version of the latest version of Toggle(to date) on my Windows 10 computer as well
