### ISSUE TITLE
Windows sync issue 7.4.18

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2156] opened 2017-03-28 06:19 UTC
/case/447400 - 2nd occurrence in 2 months despite newest version, logs included

**Comment by IndrekV** [comment] 2017-03-29 13:07
@nicktoggl This is caused by a large amount of unsynced entries. Current fix is to export data from local database and import csv. 

This fix is next on my list so in few weeks we should get this issue fixed.

**Comment by IndrekV** [comment] 2017-04-28 07:46
This is fixed with converting to api v9 #2047

**Comment by IndrekV** [comment] 2017-04-28 07:47
Updated version will be in beta today.

**Closed by IndrekV** 2017-04-28 07:46 UTC
Labels: windows

**Comment by IndrekV** [comment] 2017-04-28 12:18
Beta release will be next week as some scenarios still need testing.
