### ISSUE TITLE
No network connection in Win app after hibernation

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1653] opened 2015-11-12 10:00 UTC
After a Windows 7 hibernation Toggle can&#39;t find the network connection.
This behaviour is random as user has reported that it's working again the next day.
Reported with desk case #212712 (also includes logs).
![network](https://cloud.githubusercontent.com/assets/12407134/11115532/ea6f9d36-8934-11e5-9b45-5a7b9b55f908.png)

**Comment by amulware** [comment] 2015-12-17 07:35
Not able to reproduce. Closing until there is more data.

**Closed by amulware** 2015-12-17 07:35 UTC
