### ISSUE TITLE
Toggl Desktop Win 7.2.219 does not suggest tasks in drop-down menu

### ISSUE THREAD

**Issue by forpeterssake** [toggl/toggldesktop#1448] opened 2015-08-06 17:01 UTC
Toggl Desktop for Windows just updated, and it changed the pop-out tray to add/edit task information. I can no longer click on the project drop-down menu and type in a project name for it to search for and bring up. It only searches at the beginning of the project name, which may be another name or number. This used to work perfectly before today's update.

**Comment by amulware** [comment] 2015-08-10 08:17
Thanks for reporting the problem!

We have been able to reproduce it, and are looking in to it.

Closing this as duplicate of #1447.

**Closed by amulware** 2015-08-10 08:17 UTC
