### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by sterndata** [toggl/toggldesktop#1326] opened 2015-05-14 11:00 UTC
Attempting to run toggl generates this error:

/TogglDesktop
QMetaType::registerTypedef: -- Type name 'QVector<' previously
registered as typedef of 'QVector<AutocompleteView*>' [1034], now
registering as typedef of 'QVector<GenericView*>' [1037].
Log path "/home/sdstern/.local/share/TogglDesktop/toggldesktop.log"
DB path "/home/sdstern/.local/share/TogglDesktop/toggldesktop.db"
./TogglDesktop: symbol lookup error: /lib64/libxcb-dri3.so.0: undefined
symbol: xcb_get_reply_fds

libxcb-dri is installed:

$ locate libxcb-dri
/home/sdstern/bin/toggldesktop/lib/libxcb-dri2.so.0
/usr/lib/libxcb-dri2.so.0
/usr/lib/libxcb-dri2.so.0.0.0
/usr/lib/libxcb-dri3.so.0
/usr/lib/libxcb-dri3.so.0.0.0
/usr/lib64/libxcb-dri2.so.0
/usr/lib64/libxcb-dri2.so.0.0.0
/usr/lib64/libxcb-dri3.so.0
/usr/lib64/libxcb-dri3.so.0.0.0
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri2.so.0.0.0.debug
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri2.so.0.debug
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri2.so.debug
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri3.so.0.0.0.debug
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri3.so.0.debug
/var/cache/abrt-di/usr/lib/debug/usr/lib64/libxcb-dri3.so.debug

System is Fedora 21 / Gnome

**Comment by tanel** [comment] 2015-05-14 11:15
looks like a duplicate of https://github.com/toggl/toggldesktop/issues/1100

maybe the tip "It can be fixed by removing libxcb.so.1 from toggledesktop/lib/, and use the lib provided by the system. At least on Fedora 21." would help?

**Closed by tanel** 2015-05-14 11:15 UTC

**Comment by sterndata** [comment] 2015-05-14 11:19
Thanks!  removeing libxcb.so.1 fixed the them problem.
