### ISSUE TITLE
Pomodoro stop issue #window

### ISSUE THREAD

**Issue by leohxj** [toggl/toggldesktop#1991] opened 2016-09-23 05:40 UTC
I am using the version v7.3.333 on Windows.
In perferences, I open Pomodoro Timer for 25mins, when 25mins is over, Toggl will popup a tips, but it start a new record in the same time, So I click the contiune or create new, it is the same effect.

I don't know is this is a problem? I used an app call "SwipeTimer" on my android device, it also has a option to set how minutes after will alert me. But it will not start a new record.

I just want when the Pomodoro over, the button in pop window do this:
- continue: keep the lastest record and go on
- create new: if set Promdoro Breat Time, enter breat Time record, otherwise, it record the lastest Promodoro record, and record a new base current time.

**Comment by IndrekV** [comment] 2016-09-23 05:54
Hi,

You are using a development version of the app. Latest stable release is 7.3.326. We are adding Pomodoro Break functionality that tracks breaks right after Pomodoro time ends. Pomodoro Break can be disabled from settings. If Pomodoro Break is not enabled no time entry is started at Pomodoro time end.

This is still in development so there can be bugs with the functionality.

**Comment by leohxj** [comment] 2016-09-23 06:13
In v7.3.326, it doesn't have the Pomodoro Break option, but when the Promodoro done, it also auto start a new record, whenever I click continue or create new...

I think when the Pomodoro done, Toggl should not immediately over current record and auto record a new one. 

Hope Pomodoro will soon integration with Toggl, I am just using Toggl a week, but deep love it :)

**Comment by IndrekV** [comment] 2016-09-23 06:23
Hi 
>continue: keep the lastest record and go on
To make the same entry continue you have to select "Save duration only" from the web app. 
Go to https://toggl.com/app/profile

![screen shot 2016-09-23 at 09 22 15](https://cloud.githubusercontent.com/assets/842229/18776064/44a83348-816f-11e6-862c-ab8adcc57a3d.png)

Then app will no create new entry and will continue tracking the same that was tracking before Pomodoro time ended.

**Comment by leohxj** [comment] 2016-09-23 07:11
Got it.
 I have select "Save duration only", But there is another issuse:
When Pomodoro done, I click continue, Toggle tips me pomodoro done again.
I think its a bug,  Toggl use current recorded total time compare with Pomodoro Time, right?

**Comment by IndrekV** [comment] 2016-09-23 07:12
Yes, There seems to be issue with continuing entry that has a duration larger than Pomodoro Timer. I'll work on a fix.

Thank you for your feedback.

**Comment by IndrekV** [comment] 2016-09-23 09:44
duplicate of #1984

**Closed by IndrekV** 2016-09-23 09:44 UTC
