### ISSUE TITLE
Windows toggl desktop freezes randomly when a task is created or changed

### ISSUE THREAD

**Issue by emmanuel-umana** [toggl/toggldesktop#1498] opened 2015-08-25 15:26 UTC
Hi Guys,

Since the last update where you add a background on task edit dialog, each time I change a time or create a new task on toggl desktop for windows randomly the app got frezzed by 10 or 15 seconds and then it continue working. This is really annoing some time, do you think there is a way to solve this?

In order to discard a performance issue. My computer has a i7, 16GB of Ram and all other programs are running smothly.

Thanks,
Emmanuel

**Comment by emmanuel-umana** [comment] 2015-08-25 16:55
I will be using online version for now. Windows version is freezing almost at any task edit. :(

Thank you in advanced for any help you can give me to fix this.

Regards,
Emmanuel

**Comment by amulware** [comment] 2015-08-25 17:04
Hey Emmanuel,

Thanks for reporting the problem!

We are aware of the issue and already looking into it. We should have a new build with some improvements out soon. Please keep an eye on this issue for more:
#1483

Closing as duplicate of the same.

**Closed by amulware** 2015-08-25 17:04 UTC

**Comment by emmanuel-umana** [comment] 2015-08-25 18:28
Thanks! :+1:
