### ISSUE TITLE
Menubar item shows up even if turned off in preferences

### ISSUE THREAD

**Issue by pauldegroot** [toggl/toggldesktop#1028] opened 2015-01-04 12:54 UTC
The menu bar timer shows up even if the checkbox for 'show menu bar timer' is turned off.
MacOsX 10.9, client 7.1.161.

**Comment by IndrekV** [comment] 2015-01-04 14:32
Duplicate of #1026
This is already fixed, but not released.

**Closed by IndrekV** 2015-01-04 14:32 UTC
