### ISSUE TITLE
Crash when filtering text in AutoComplete

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2872] opened 2019-03-18 03:39 UTC
There is a crash on latest Window version that it's crashed as soon as we move the selection in Auto Complete View during searching Description.

### 💻 Environment
Platform: Windows
OS Version: Windows 10
Toggl Version: Stable 7.4.345

### 🐞 Actual behavior
- It's crashed 💥 

### 💯 Expected behavior
- Should work without crashing 💯 

### 🔨 Steps to reproduce
1. Create new time entry 
2. Type something to start filtering 
3. Arrow up 
4. (after noticing there's still too many items) continue typing to further filter the list 
5. Try to move again; crash.

**Comment by TheSoloJake** [comment] 2019-03-18 15:35
[case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/21125221696) for affected user

**Comment by scmancuso** [comment] 2019-03-21 13:43
I've noticed a similar bug, which is probably related. For me, the issue occurs when searching for a time entry, after already selecting a project.
![image](https://user-images.githubusercontent.com/4419710/54755915-b7b41000-4bac-11e9-9d59-2ca3172b0c5e.png)
In this image, if I continue typing "Computer updates" and then try to use the up or down arrow to select the item in the dropdown, the app crashes.

**Comment by skel35** [comment] 2019-03-25 10:36
Duplicate of #2508

**Closed** 2019-03-25 11:26 UTC
Labels: bug, windows
