### ISSUE TITLE
Allow Windows Mini Timer to not stay on top

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggldesktop#2393] opened 2018-02-09 17:06 UTC
From case/641473: 

> I have two monitors. Monitor 2 is my main screen. I have a timer of the task I am working on on Monitor 2 in the upper left corner. This timer is separate from the Toggl app on my desk. This timer is staying on top of everything. This timer hides pinned tabs on google chrome.

**Comment by skel35** [comment] 2019-07-11 12:23
Is this a feature request to make mini timer not stay on top of all windows?
What does it have to do with multi-monitor setup?

**Comment by IndrekV** [comment] 2019-07-17 05:57
The issue seems to be with tooltip being frozen and on top of other applications. This is the screenshot provided.

![image](https://user-images.githubusercontent.com/842229/61350606-cbc50100-a870-11e9-8900-f871dbbb9ee9.png)

I know we have looked into this before and did not find a solution. Feel free to close this if you can't reliably replicate or find a cause for the misfunctioning tooltip. This seems like some kind of an operating system issue.

**Comment by skel35** [comment] 2019-07-17 07:56
Couldn't reproduce it, but I'm not even sure what tooltip is that, haven't found any with this format. 
If it's still an issue, I hope someone will report it again with steps to reproduce or better clues.

**Closed by skel35** 2019-07-17 07:56 UTC
Labels: windows
