### ISSUE TITLE
Can't select installing location for Toggl Desktop Windows

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl/toggldesktop#2788] opened 2019-02-05 08:33 UTC
There is a report that Kornelije couldn't manually select the location, where he desire to install the TogglDesktop app in Windows.

### 💻 Environment
Platform: Windows
OS Version: Windows 10
Toggl Version: All versions

### 🐞 Actual behavior
- Unable to select custom location for installing the app
- The browser is disable.

![image](https://user-images.githubusercontent.com/5878421/52261174-9096db80-297c-11e9-81d0-f9508c2a85f1.png)

### 💯 Expected behavior
- Able to select custom install location.

### 🔨 Steps to reproduce

1. Download Windows version
2. Run Toggl Desktop Installer.

**Comment by IndrekV** [comment] 2019-02-05 11:18
This is currently intended behavior. We had a lot of reports that users were unable to install the app if it needed admin right to install. If we decide to change this we will need to add the selection into the installer that states "For this user" or "all users" and then we allow user to select location.

**Comment by ricotheque** [comment] 2019-04-11 14:27
Related [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21541887490)

**Comment by IndrekV** [comment] 2019-06-12 08:15
Will be fixed with #2955

**Closed by IndrekV** 2019-06-12 08:15 UTC
Labels: bug, windows

**Comment by lchutny** [comment] 2019-09-01 15:51
This is still an issue (Sept 1, 2019). Am not installing Toggl Desktop because it doesn't let me choose a location for the install.
