### ISSUE TITLE
Keyboard shortcut for Linux to start/stop a running timer?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggldesktop#1877] opened 2016-04-20 15:59 UTC
Dear all,

Inspiration comes from:

> @IndrekV This just gave me an idea. How about adding a keyboard command? The command would stop the current entry and if there's no entry running it would continue the last entry. It could be something like: ctrl+shift+t

Source: https://github.com/toggl/toggl-button/issues/430#issuecomment-212450757

What do you think of this for the Desktop version?

Thankfully, 

Robert

**Comment by IndrekV** [comment] 2016-04-20 16:09
Various keyboard shortcuts including stop timer are already present in Toggl Desktop.

The global shortcuts are best for starting and stopping timer at any moment.

See these articles for reference:
https://support.toggl.com/toggl-desktop-for-windows/#keyboard
https://support.toggl.com/toggl-desktop-for-mac-osx/#shortcuts

**Comment by orschiro** [comment] 2016-04-20 16:33
Dear @IndrekV,

Are there any Linux equivalents?

Warmly,

~Robert

**Comment by IndrekV** [comment] 2016-04-20 16:38
No keyboard shortcuts in linux for now.

**Comment by orschiro** [comment] 2016-04-20 16:57
I edited my issue title to specify for Linux.

Can we re-open this issue?

~Robert

**Comment by IndrekV** [comment] 2016-07-05 14:16
duplicate of #1785

**Closed by IndrekV** 2016-07-05 14:16 UTC

**Comment by IndrekV** [comment] 2016-07-06 08:19
@orschiro This has been implemented and will be available in the next release.

**Comment by orschiro** [comment] 2016-07-06 08:39
Fantastic, thank you!

Any plans when the next Ubuntu Linux package will be released?

**Comment by IndrekV** [comment] 2016-07-06 09:43
Beta version is planned to the end of this week on beginning of next. Few weeks after that it will be in stable channel.
