### ISSUE TITLE
Runs only in background on auto startup on Windows

### ISSUE THREAD

**Issue by ygale** [toggl/toggldesktop#3348] opened 2019-09-24 05:02 UTC
### 💻 Environment
Platform: Windows
OS Version: 10.0.18362
Toggl Version: 7.4.529
### 🐞 Actual behavior
Toggl starts automatically at startup as configured, but only in the background.
There is no Toggle Desktop window. Running the EXE again does not help.

### 💯 Expected behavior
When configured to start automatically, the Toggle Desktop window opens at startup.
When running only in the background, running the EXE again causes the window to open.

### 🔨 Steps to reproduce
1. Download and install the installer EXE.
2. Make sure Toggl Desktop is added to startup items. Sorry, I don't remember if that happened as part of the installation, or if I did that manually afterwards.
3. Restart the computer.

### 📦 Additional info
Possibly related to #3347.

**Comment by lise-toggl** [comment] 2019-09-24 06:08
Hi @ygale, thanks so much for the report! I think it might be the same is this issue: https://github.com/toggl/toggldesktop/issues/3285

Could you try the latest beta and let us know if it's fixed? You can get the installer from here: https://toggl.github.io/toggldesktop/download/windows-beta/

**Comment by ygale** [comment] 2019-09-24 06:22
OK I'll try to get to it soon.

I found a workaround:
1. Disable the Toggl startup item in Task Manager.
2. Restart the computer.
3. Run Toggl Desktop.
4. Pin Toggl Desktop to the taskbar.
5. Re-enable the Toggl startup item.
6. On startup, if the Toggle Desktop window does not appear, click the Toggl icon on the taskbar.

This might also work, but I didn't try it:
1. Kill all Toggl processes in Task Manager.
2. Run Toggl Desktop.
3. Pin Toggl Desktop to the taskbar.
4. On startup, if the Toggle Desktop window does not appear, click the Toggl icon on the taskbar.

**Comment by skel35** [comment] 2019-09-24 06:30
Hi @ygale!
Yes, these are valid workarounds, but the issue is already fixed in beta, and the stable version with the fix will be available very soon.
You can also disable/enable Toggl startup using Toggl Desktop cogwheel button->Preferences->Run the app on Windows login.

**Closed by skel35** 2019-09-24 06:30 UTC

**Comment by ygale** [comment] 2019-09-24 06:35
Excellent, thanks!
