### ISSUE TITLE
Name field cursor stuck after selection of previous entry

### ISSUE THREAD

**Issue by HansCronau** [toggl/toggldesktop#1654] opened 2015-11-12 19:19 UTC
Expected based on web interface:
After choosing a previous entry by typing its name in the name field, I can move the cursor to edit its name.

Actual behaviour:
After choosing a previous entry using the name field, the cursor freezes (somewhat right to the name). Left, Right, Home, End, and mouse clicking don't move it.

Workaround:
Start typing. Characters will appear at the end of the name entry and the cursor will move as expected again.

System specs:
Toggl Desktop 7.3.157 (beta)
Windows 7 64bit

**Comment by amulware** [comment] 2015-11-13 07:26
Thanks for reporting the problem!

This is a known issue that unfortunately is very hard for us to reproduce reliably. (I've seen it happen with several different text boxes in the app)

Does the cursor freeze every single time for you in this case?

**Comment by HansCronau** [comment] 2015-11-13 11:36
I was about to say "yes", when I tested it again. For once, the cursor did not freeze, after which it continued this behaviour. It indeed appears very random.

Possibly noteworthy observations:

- If the cursor is stuck and I start typing (previously mentioned workaround), the text now appears to the _left_ of the entry, instead of the previously reported right.
- When the cursor freezes by selecting an entry from the drop-down, the cursor stays where is was before selection. To clarify: it stays _exactly_ where it is on the screen. It _will_ appear in the middle of a character if it happens to be there.
- Selecting another entry from the drop-down, using the arrow keys, also makes the cursor visible again. It will appear _left_ to the entry.
- Selecting another entry from the drop-down, using the mouse, also makes the cursor visible again. It will appear _right_ to the entry.
- Possibly completely unrelated: cycling through previous entries in the drop down (with the Up and Down keys), some entries "randomly" won't get highlighted. Selecting them again (Up, Down) often will, unless the drop-down is completely frozen, which so far seems to happen randomly.

**Comment by amulware** [comment] 2015-12-15 13:40
I am currently not able to reproduce this issue. It may well still be there, but I have not seen it in quite a while. Here is hoping that it got magically fixed! (In either case, closing issue until we are able to reproduce it, or have some sort of clue what might be causing this.)

**Closed by amulware** 2015-12-15 13:40 UTC
Labels: bug, windows
