### ISSUE TITLE
windows: multimonitor support broke

### ISSUE THREAD

**Issue by slav** [toggl/toggldesktop#1397] opened 2015-06-28 13:58 UTC
It used to be that if toggle is on the left side of my right monitor the task properties window would appear on the right side of toggl window. Now it seems that toggle likes task properties window position (left or right off the main window) is determined by main window position relative to the entire desktop, not to the window. This forces properties window to now always show up on the left, on a different monitor, making it quite inconvenient
![togglmultimonitor](https://cloud.githubusercontent.com/assets/350987/8396621/385622ce-1d7c-11e5-91dc-068a9f56dc09.png)
 to use. Attached is the screenshot.

**Comment by waterfowladdict** [comment] 2015-07-02 12:50
After I installed the latest release, I've been experiencing the same issue.

**Comment by justintilton** [comment] 2015-07-09 13:46
Using v7.2.172
In single display (laptop) HW config. I had no display problems. Added a monitor to laptop via HDMI and now any window overlay of the toggl window will clear some parts of the window:

![image](https://cloud.githubusercontent.com/assets/12625806/8596657/f71ec7ec-2650-11e5-8265-369db75de770.png)

When I mouse over the toggle window each section will redraw:

![image](https://cloud.githubusercontent.com/assets/12625806/8596750/6e1c58fa-2651-11e5-9721-52df684b14a2.png)

**Comment by amulware** [comment] 2015-07-09 15:49
Thanks for reporting this, @justintilton!

Sounds like it may be related to #1375. We are working on resolving that issue and hope to have these problems sorted out soon.

It is a bit odd though that it would occur only when you connect additional monitors.

Can you let us know what CPU and GPU you have?

**Comment by justintilton** [comment] 2015-07-09 18:35
Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz

NVIDIA GeForce GT 555M

Intel HD Graphics

**Laptop Automatically transitions between NVIDIA graphics and Intel
Integrated Graphics (NVIDIA Optimus)

-- justin

**Comment by amulware** [comment] 2015-07-10 05:42
Thanks for letting us know!

We are still not sure what exactly the problem is, but hopefully we will be able to find a pattern.

In either case, we should be able to release a fix for your problem soon. Make sure to keep an eye on #1375.

**Comment by justintilton** [comment] 2015-07-10 14:59
Thank you! I'll let you know if I notice anything else that might be of use
tracking down the issue... -- justin

**Closed** 2015-07-13 11:46 UTC
Labels: bug, windows
