### ISSUE TITLE
ksmserver: Client canceled shutdown.

### ISSUE THREAD

**Issue by StanczakDominik** [toggl/toggldesktop#2122] opened 2017-02-11 18:03 UTC
Running the client prevents the system from shutting down on Arch Linux running KDE Plasma 5.9.

This is the relevant log from journalctl:

> Feb 11 18:58:28 dpc org_kde_powerdevil[1613]: powerdevil: Scheduling inhibition from ":1.10" "ksmserver" with cookie 6 and reason "Shutting down system"
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: saveSession is  true
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: Saving legacy session apps
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: Done saving  1  legacy session apps
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: clients should be empty,  false
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:28 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:29 dpc ksmserver[1541]: ksmserver: completeShutdownOrCheckpoint called
> Feb 11 18:58:29 dpc ksmserver[1541]: ksmserver: 7
> **Feb 11 18:58:29 dpc ksmserver[1541]: ksmserver: Client  "/opt/toggldesktop/TogglDesktop"  ( 106470630000148683589700000015410032 ) canceled shutdown.**
> Feb 11 18:58:29 dpc org_kde_powerdevil[1613]: powerdevil: Releasing inhibition with cookie  6
> Feb 11 18:58:29 dpc org_kde_powerdevil[1613]: powerdevil: It was only scheduled for inhibition but not enforced yet, just discarding it

There's no mention of any shutdown attempt in the log, as given by `toggl --log-path toggllog`.

**Comment by IndrekV** [comment] 2017-08-25 11:48
Duplicate of #1645

**Closed by IndrekV** 2017-08-25 11:48 UTC
Labels: bug, linux
