### ISSUE TITLE
#2480: Autocomplete dropdown is sometimes not tall enough in the Edit View

### ISSUE THREAD

**Issue by MartinBriza** [toggl/toggldesktop#2569] opened 2018-09-06 10:13 UTC
Doesn't happen deterministically (or I just couldn't find the triggering condition) but after a few edits both in the Description and Project field, the dropdown _can_ show being able to display only one entry (instead of about 6 it shows regularly).

Part of #2480

**Comment by MartinBriza** [comment] 2018-11-08 15:42
Again, I'm convinced this issue was fixed, or became much harder to reproduce. Does this still happen to you, @IndrekV ?

**Comment by IndrekV** [comment] 2018-11-09 12:36
I'll test it out and close it if I can't reproduce.

**Comment by IndrekV** [comment] 2018-11-12 04:58
Unable to reproduce.

**Comment by IndrekV** [comment] 2018-11-12 05:28
seems to be happening with description field in edit view. If you filter the items the filter is not reset and after clearing the field you do not see all the items.

**Comment by IndrekV** [comment] 2018-11-12 10:36
The last comment formulate into new issue -  #2625

**Comment by IndrekV** [comment] 2018-12-12 12:37
out of date

**Closed by IndrekV** 2018-12-12 12:37 UTC
Labels: linux
