### ISSUE TITLE
Time Entry date editor not working on macOS app

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggldesktop#2361] opened 2018-01-23 23:48 UTC
case/587687:

"I used to be able to then edit that task's date and start/stop time to match what I need to record. Now I can only enter the time range - but I can't move it to another date (future or past).

Some UI irregularities that lead me to believe that something is not right... the trashcan in the pop-up dialog is underneath the 'Tags:' UI. Also, selecting the duration and time fields does not make any calendar UI appear like I remember it doing."

User has already tried local data clearing and reinstall, to no effect.

(screenshot or irregular UI in case; contains user information so not sharing that here)

**Comment by ricotheque** [comment] 2018-01-24 03:12
The edit entry dialog of an El Capitan user (case/634218) has a similar broken layout. The only difference is that the date textbox/dropdown does not appear at all.

(screenshot in case)

**Comment by IndrekV** [comment] 2018-01-24 11:17
duplicate of #2342

**Closed by IndrekV** 2018-01-24 11:17 UTC
