### ISSUE TITLE
Windows app crashing after upgrade

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1286] opened 2015-04-08 08:53 UTC
System.ComponentModel.Win32Exception was unhandled
Message: An unhandled exception of type
'System.ComponentModel.Win32Exception' occurred in System.Windows.Forms.dll
Additional information: Error creating window handle.
More: 148393

**Comment by tanel** [comment] 2015-04-09 14:55
most probably a) the app leaks window handles - check what new UI components have been added *or* b) user has simply too many time entries to render.

**Comment by tanel** [comment] 2015-05-13 15:30
duplicate of #1139

**Closed by tanel** 2015-05-13 15:30 UTC
Labels: bug, windows
