### ISSUE TITLE
Windows client freezes when typing project/task/description

### ISSUE THREAD

**Issue by bernhof** [toggl/toggldesktop#2251] opened 2017-08-24 12:09 UTC
In a workspace <s>with around 900 tasks and a few hundred projects</s> _(I've found that this occurs even in small workspaces with only few projects, tasks etc.)_, the Windows client consistently hangs a couple of seconds whenever I start typing in the "What are you doing" field or, when editing an entry and typing the project/task name. It freezes as soon as I've typed a single letter. As it unfreezes the list of suggestions is then displayed.

To mitigate this, I'd suggest doing one or more of the following
- make the suggestion lookup asynchronous so that the client at least stays responsive
- only do lookup when 3 or more characters have been entered
- limit the number of results being returned to the client
- only look up suggestions after a short delay (e.g. I type "web", then pause shortly, after which only suggestions for "web" are requested and shown to me, not for neither "w" nor "we")

**Comment by bernhof** [comment] 2017-09-15 11:44
As a follow-up to this I should add that the way we're using Toggl is that almost every entry is different, since people usually follow-up with a few notes about what they spent their time on this time around. This may be what's causing the delay in the app, since the suggestions include a distinct list of previous entries _and_ their description (which in our case could be a very long list!)

**Comment by bernhof** [comment] 2017-09-22 07:04
Just found similar issue #1660 which claims this was solved in #1790. However, the issue persists.

**Comment by IndrekV** [comment] 2017-10-05 09:21
This is indeed not fixed. I'm able to replicate this when the account has bigger amount of data (things to load into the autocomplete). Windows autocomplete is solved a bit different than the other platforms and I suspect that this solution is the reason of the slowdown.

**Comment by pfeigl** [comment] 2018-01-19 14:59
Is there any progress on this. We are pretty much affected with our whole company and people start looking for alternatives :( We rarely can update a single entry without having the application hang for several seconds.

**Comment by IndrekV** [comment] 2018-01-20 11:43
Hi, thank you for showing your interest in this issue. We have found the cause for this and tried to fix it but discovered that the issue is bigger than we first estimated. To properly fix this we need to rewrite some fundamental parts of data handling. We plan to start work on it next week or the week after. This is one of the top items in our todo list.

Thank you for your patience and I hope we can bring some good news soon.

**Comment by pfeigl** [comment] 2018-03-28 11:38
@IndrekV is there any kind of timeline on this? Can we help testing somehow?

**Comment by IndrekV** [comment] 2018-03-28 11:46
We're in mid-development. We've found the cause and worked out how to solve the issue. We are rewriting this part of the autocomplete. I hope we can share updated version in a week or two.

**Comment by IndrekV** [comment] 2018-05-11 21:18
closed together with #2042 . Will be released to beta next week

**Closed by IndrekV** 2018-05-11 21:19 UTC
Labels: bug, windows
