### ISSUE TITLE
Edit window not opening on the correct side

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1640] opened 2015-11-04 08:02 UTC
The edit window opens left of the main window if the main window is on the right side of the screen, but I move the main window a little bit to the left, the edit window moves to the right of it, although there&#39;s not enough space to show the whole edit window. Could you please fix this behaviour in order to always show the whole edit window? Thanks.

**Comment by amulware** [comment] 2015-11-04 10:00
For me the behaviour is the intended one:
1. The edit popup opens on the right side if and only if there is enough space.
2. Otherwise it opens on the left (where there may not be enough space, nothing special is done in that case).

User seems to report 1. not being the case, which I cannot reproduce at the moment.

**Comment by amulware** [comment] 2015-11-05 09:02
Closing until we can reproduce or get more information.

**Comment by amulware** [comment] 2015-11-09 09:10
Another user has reported the same, and I did see the problem myself the other day. May have to do with higher DPI settings (though I was not able to reproduce it with any settings when I tried).

Needs investigation, debugging and fixing.

**Comment by amulware** [comment] 2015-11-11 11:02
I can now confirm that the problem is related to DPI settings. Specifically, WPF gives all positions/sizes DPI aware (not actual pixels), while the code we use to determine the size of the screen returns actual pixels. We'll probably have to transform one set of coordinates to the other and do the calculations that way.

**Closed** 2015-11-23 12:13 UTC
Labels: bug, windows
