### ISSUE TITLE
duration is not fully visible in the linux app, Ubuntu 14.04

### ISSUE THREAD

**Issue by tanel** [toggl/toggldesktop#1144] opened 2015-02-16 18:29 UTC

**Comment by tanel** [comment] 2015-02-16 18:56
To clarify, it looks like the time only gets cut off when the task name is long.

**Comment by IndrekV** [comment] 2015-03-18 14:12
Unable to reproduce in master at the moment. If you can produce this issue please write description. If not close the issue.

**Comment by IndrekV** [comment] 2015-03-26 20:01
Might be connected to Hi DPI #808

**Comment by IndrekV** [comment] 2015-03-27 09:45
User reports this happening with 120 DPI.

**Closed** 2015-03-30 11:40 UTC
Labels: bug, linux
