### ISSUE TITLE
Duration is cutoff in timer

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggldesktop#1107] opened 2015-02-03 18:41 UTC
More info in 128956

**Comment by tanel** [comment] 2015-02-03 19:33
fixed in master

**Comment by sanchitgoyal01** [comment] 2015-02-06 18:18
Is it still unresolved ?

**Comment by tanel** [comment] 2015-02-06 19:27
Yes, it looks like the fix I did did not fix every format available in the app.

**Comment by tanel** [comment] 2015-02-09 06:15
Should be fixed in master; I cannot reproduce the issue on Ubuntu 14. Please try the latest dev build, whoever still has the issue.

**Closed by tanel** 2015-02-09 06:15 UTC
Labels: bug, linux
