### ISSUE TITLE
UX: Responding to other Toggl tracking tools

### ISSUE THREAD

**Issue by fiasco** [toggl/toggldesktop#1443] opened 2015-08-03 20:49 UTC
I use Chrome's toggl button extension to help me track time on projects in the browser. Its really useful, but since it don't capture everything, I keep Toggl Desktop (OSX) running also to (A) make sure I'm tracking the right thing and (B) switch projects when Toggl Button isn't available for what I want to context switch to (like using another app or website not supported by the extension).

The issue is, when I begin tracking time with Toggl Button in the browser, I don't see that update immediately in Toggl Desktop. Worse still, I can sometime be double tracking time while Toggl Desktop continues to track time against what I was previously tracking.

The only work around to this is to bring the Toggl Desktop app into focus and force a sync (Apple + R) which then updates this. But that essentially defeats the purpose of using Toggl Button to be able to track time in the browser, without having to switch focus.

This hasn't always been an issue. In previous versions of Toggl Desktop, I've seen the app update almost instantly when I've switched projects in the browser.

**Comment by johansolve** [comment] 2015-08-04 09:54
I'm bothered by this too.

**Comment by banjerluke** [comment] 2015-08-10 18:53
This is a big issue for me. It's probably related that sometimes I'll stop tracking time on one computer, but then open up Toggl on another computer and it will continue tracking the time – suddenly, a 30 minute billable period becomes a 28 hour work period... not good for keeping track of client hours! I am nervous to use Toggl Desktop now...

**Comment by johansolve** [comment] 2015-08-11 07:32
All of a sudden the desktop client updates immediately (within 1-2 seconds)

**Comment by IndrekV** [comment] 2015-08-11 07:35
This issue is connected to websocket connection we use for live updates. The connection can fail at times and is then restarted. If the connection is up then everything will update almost instantly. If the connection has failed for some reason we sync the data with an interval (about 5-15 minutes) until the websocket connection is re-established.

**Comment by IndrekV** [comment] 2015-08-11 07:39
Also the websocket failing was caused by some backend issues we were having with the live updates system. These issues should be fixed now. I'll close this issue. If someone is still experiencing slow updates please re-open or create a new issue and we will take another look at this.

**Closed by IndrekV** 2015-08-11 07:39 UTC
