### ISSUE TITLE
windows: parts of the toggle window go blank

### ISSUE THREAD

**Issue by slav** [toggl/toggldesktop#1396] opened 2015-06-28 13:52 UTC
Attached is the screenshot of the problem. It happens randomly. Forcing redraw (by moving cursor over it or moving another window on top of it fixes the problem, just for a little bit).

This started with the latest release 7.2.172

![togglblank](https://cloud.githubusercontent.com/assets/350987/8396620/2ca8fe2e-1d7c-11e5-8506-a1a3b1cee78d.png)

**Comment by jackplug** [comment] 2015-06-29 14:30
I seeing the same thing - the desktop appears where the items list is supposed to be - the items only reappear when I mouse over (or minify the window, or maximise the window)
Release 7.2.172 running on Win Pro 8.1

**Comment by amulware** [comment] 2015-06-29 14:57
Hey guys,

Thanks for letting us know about the problem.
We are already investigating, and hope to have a solution soon.

From what we know so far, we suspect that out of date drivers might be part of the cause of this problem.
If you got a few minutes, could you update your graphics drivers and report back if the problem is still occurring?

Either way, we will continue to investigate as well.
Sorry for the inconvenience!

(Closing as duplicate of #1375)

**Closed by amulware** 2015-06-29 14:57 UTC
