### ISSUE TITLE
Editing exiting entry input loses focus

### ISSUE THREAD

**Issue by juriejan** [toggl/toggldesktop#2855] opened 2019-03-12 07:35 UTC
Seems to have been a similar issues: #1995, #2028, #2070 

### 💻 Environment
Platform: macOS
OS Version: macOS 10.14.2
Toggl Version: 7.4.365

### 🐞 Actual behavior
When I'm editing an existing entry the focus jumps to the input containing the 'What are you working on?' placeholder text. This seems to happen all the time while I'm attempting to type in a new value anywhere in the open entry, but sometimes the behaviour stop long enough for me to enter the desired value.

### 💯 Expected behavior
The focus should stay on the input that I'm currently entering a value into. 

### 🔨 Steps to reproduce
1. Start and stop entry to create a new entry.
2. Click on the entry to open the edit view.
3. Click on the 'Duration' input to change focus to it.
4. While typing or even before typing the focus changes to the 'What are you working on?' input.

**Comment by IndrekV** [comment] 2019-03-12 07:41
Duplicate of #2833
Will be fixed with #2854

Thank you for reporting, we're already working on it.

**Closed by IndrekV** 2019-03-12 07:41 UTC

**Comment by dagoodma** [comment] 2019-04-13 06:11
I'm having the same issue. It keeps switching focus to the "What are you working on?" input box in the main window right when I'm trying to type in a time or description in the edit time entry window. This bug is super annoying. It makes the mac desktop version of toggl almost completely unusable.

Any updates on a fix? When will it be released?  I would greatly appreciate a rollout or being able to build it from source. @IndrekV Do you have a branch for the fix that I can try?

Platform: 
OS Version: 
Toggl Version:

**Comment by dagoodma** [comment] 2019-04-13 06:15
> I'm having the same issue. It keeps switching focus to the "What are you working on?" input box in the main window right when I'm trying to type in a time or description in the edit time entry window. This bug is super annoying. It makes the mac desktop version of toggl almost completely unusable.
> 
> Any updates on a fix? When will it be released? I would greatly appreciate a rollout or being able to build it from source. @IndrekV Do you have a branch for the fix that I can try?
> 
> Platform: macOS
> OS Version: macOS 10.13.6
> Toggl Version: 7.4.365

Oops, I found the 7.4.371 beta in #2854 . Nevermind
