### ISSUE TITLE
Linux - logging out causes the window to close

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#2249] opened 2017-08-22 19:37 UTC
linux_native_app/7.4.52

> Under XFCE, Toggl desktop still has the behaviour that logging out causes the window to close (if open) after which the logout is cancelled. Presumably the WM is sending Toggl a "query-quit"; message, which is triggering the Toggl window to close, but returning a "cancel logout" message to the WM. To work around this I've started closing the Toggl window before logging out, leaving the icon running in the tray. I've noticed that some of the time, the Toggl process stays running after I've logged out, which prevents it auto-starting at login the next day. Killing the old process manually allows me to re-run it, manually.

Case #535137

**Comment by IndrekV** [comment] 2017-08-24 21:30
Duplicate of #2122

**Closed by IndrekV** 2017-08-24 21:30 UTC
