### ISSUE TITLE
No control over fonts

### ISSUE THREAD

**Issue by ericvanroy** [toggl/toggldesktop#1387] opened 2015-06-25 13:26 UTC
I am using the windows desktop version. 
Somehow my fonts don't size correctly anymore. I am not sure how this changed, but there is no control over changing this, As you can see in the attachment, words are truncated, and the "start-time" can't be viewed/adjusted
![toggl](https://cloud.githubusercontent.com/assets/6919056/8355217/851e93f4-1b13-11e5-94de-d053e45a8a3e.png)
Thank you

**Comment by amulware** [comment] 2015-06-25 13:30
Thanks for reporting the problem!

We are aware of the issue and looking into it. I hope we can have it resolved soon.

For now, as a work-around that  should help to some degree, you can disable display-scaling for TogglDesktop.  
See here: http://ccm.net/faq/32589-windows-8-1-disable-display-scaling-on-high-dpi-settings

That should improve things at least a bit for now.

Sorry for the inconvenience and thanks for your patience!

(closed as duplicate of #1379)

**Closed by amulware** 2015-06-25 13:30 UTC
