### ISSUE TITLE
Windows app crash after autocomplete selection task with already selected project

### ISSUE THREAD

**Issue by Rosnicka** [toggl/toggldesktop#2586] opened 2018-10-05 09:02 UTC
Windows app crash in this scenario.
1) use autocomplete input to select project of task
2) then start to type name of task and try to select task from autocomplete with keyboard down arrow
3) app crash

**Comment by skel35** [comment] 2019-05-13 11:27
Duplicate of #2872, #2508.
Fixed in #2887

**Closed by skel35** 2019-05-13 11:27 UTC
Labels: windows
