### ISSUE TITLE
Display does not redraw/render correctly

### ISSUE THREAD

**Issue by Catmacey** [toggl/toggldesktop#1408] opened 2015-07-07 09:48 UTC
The main toggl desktop window does not redraw correctly when the pop-up issue panel is open.  It displays fragments of the list of tasks and other bits of information over the top the lower part of the main window (what should be the task list). Moving the mouse of over the window triggers a redraw but still leaves areas as unrendered or transparent.
I have attached a redacted screenshot illustrating the problem.
![toggl_badredraw](https://cloud.githubusercontent.com/assets/3985260/8543601/0e2b7a7a-249e-11e5-8b13-205ed7d6ffe3.PNG)

Version 7.2.172 Window 7.

**Comment by tanel** [comment] 2015-07-07 11:05
It looks like a duplicate of #1375

**Closed by tanel** 2015-07-07 11:05 UTC

**Comment by Catmacey** [comment] 2015-07-07 11:47
Yes. Now you mention it it does look like a dupe. Sorry.
