### ISSUE TITLE
Mac OSX app display layout issue

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2365] opened 2018-01-24 23:53 UTC
case/634457 screenshot included in case <-

"Have had this issue in the past. It has returned. When starting a new job, the desktop interface is not working/displaying correctly. In the bottom left, you can see that the trash, tags, and slider bar are all jammed up. Also, when I add a new project, there is no option to select a color for it. In the past, I've trashed the cache and removed some kopsik (?) file(s) and reinstalled the desktop app, and eventually had to reinstall a previous release to fix it. I've deleted the cache, and reinstalled the app, but no fix now. Stays the same. Image attached to show new project window. Any help would be appreciated. MAC OS 10.11.6"

**Comment by IndrekV** [comment] 2018-01-25 07:20
duplicate of issue #2342

**Closed by IndrekV** 2018-01-25 07:20 UTC
Labels: macOs
