### ISSUE TITLE
A lot of our clients/projects doesn't show up in the desktop app for Mac

### ISSUE THREAD

**Issue by joakimc** [toggl/toggldesktop#2284] opened 2017-10-05 08:44 UTC
Some clients/projects doesn't show up in the desktop app for Mac, neither in autocomplete nor in the Project dropdown.

In the online timer everything works just like it should. None of the projects are set to private or anything.

**Comment by IndrekV** [comment] 2017-10-05 09:07
Please specify the platform you are using and also is it possible that the names of missing project are same as other projects that are visible in the dropdown. (project name is same but clients are different)

**Comment by joakimc** [comment] 2017-10-05 09:16
That's possible, but in that case the other projects aren't showing up either. For instance, I have a project called "web" for a client, let's call him "Client A". When writing "web" in the Project-field, a lot of projects containing the letters "web" are showing up, but not the project called "web" for this client, "Client A". When typing "Client A" nothing shows up. In the dropdown list none of this are showing.

Like I said, this works perfectly in the online user interface, and I assume this is supposed to work in the same way in the Desktop app? None of the projects are set to Private by the way – they're available to the whole team.

**Comment by IndrekV** [comment] 2017-10-05 10:21
The issue is not with the project rights but with the autocomplete element used in the mac app. We have plans to change the autocomplete to fix this issue. Sadly no clear ETA for this right now. This is connected to issue #1768

**Comment by IndrekV** [comment] 2018-03-26 09:53
Fixed with #1768

**Closed by IndrekV** 2018-03-26 09:53 UTC
Labels: bug, macOs
