### ISSUE TITLE
Project selection dropdown has no suggestions (Windows, 7.2.233)

### ISSUE THREAD

**Issue by codeman38** [toggl/toggldesktop#1447] opened 2015-08-06 14:05 UTC
In version 7.2.233 for Windows, the project selection box in the task editor popup is completely empty, even though I have multiple projects defined. If I type into the field, it doesn't match any of my existing projects, even when I know the project name is present. If I use the pull-down menu, the only thing that is listed is "No project".

**Comment by tanel** [comment] 2015-08-06 14:18
Working on it!

**Comment by killermouse0** [comment] 2015-08-07 11:43
+1, same issue. Thanks @tanel !

**Comment by amulware** [comment] 2015-08-12 07:16
This is now fixed in the latest dev build, available here:
https://assets.toggl.com/installers//TogglDesktopInstaller-7_2_261-2015-08-11-23-59-06.exe

**Closed by amulware** 2015-08-12 07:16 UTC

**Comment by RichyA** [comment] 2015-08-12 09:10
Thanks for the new build.

The project list now populates correctly, but it isn't quite working as I'd expect. The projects are listed in the dropdown, but when I select one, the list doesn't close and the value isn't inserted into the field. However, the task record IS updated with the selected project, as visible in the main Toggl window. If you close the details panel and reopen it, the project is displayed correctly.

Additionally (and I know this should probably be logged separately) I now can't change the start time of a task that is still running, and changing the start time of a previous task doesn't update the details when you tab out of the field - you have to close and reopen the details panel.

**Comment by amulware** [comment] 2015-08-12 09:13
Thanks for testing the build!

We will look into the other issues you mention (we can already reproduce the project-selection thing).
Hopefully we can iron these problems out soon as well.

**Comment by amulware** [comment] 2015-08-12 11:19
Just a quick confirmation: We found the cause of the strange project selection behaviour and the start-time thing you mentioned.

In fact, the entire edit window does not update correctly right now. We should have this sorted out soon.
