### ISSUE TITLE
Linux: Help menu points to incorrect URL

### ISSUE THREAD

**Issue by Perturbatio** [toggl/toggldesktop#2112] opened 2017-01-25 10:25 UTC
When using the help option from the app (v7.4.7) on linux, the URL provided is for the OSX version (https://support.toggl.com/toggl-desktop-for-mac-osx/), it should be https://support.toggl.com/toggl-desktop-for-linux/

**Comment by IndrekV** [comment] 2017-02-03 05:31
duplicate of #2084

**Closed by IndrekV** 2017-02-03 05:31 UTC
