### ISSUE TITLE
Timer info disappears from the menu bar

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggldesktop#1963] opened 2016-08-05 09:58 UTC
osx_native_app/7.3.319
User reports:
I have both "Show timer on menu bar" and "Show project on menu bar" enabled. This works fine if either Toggl or Finder are in focus, but if I focus on a window for any other app, the timer info disappears from the menu bar. 
El Capitan (10.11.6)
Case with logs: #320675

**Comment by IndrekV** [comment] 2016-09-02 15:21
Unable to reproduce this right now. I'll ask more details.

**Comment by IndrekV** [comment] 2016-09-23 10:45
Have not received info and other reports of this issue. Closing this for now.

**Closed by IndrekV** 2016-09-23 10:45 UTC
Labels: bug, macOs
