### ISSUE TITLE
App crash on close

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggldesktop#2201] opened 2017-06-19 04:26 UTC
'Toggl desktop app freezes on my first attempt at closing the program. Every time, whether using shortcut or menu to quit. Subsequent opening and then closing of app is fine, but if I shut down or sleep the computer and open app, it freezes upon trying to quit. Running 7.4.48 on Mac OSX'

case/488886

**Comment by mtsweir** [comment] 2017-06-19 04:41
Same for me, when I close toggl desktop the app is still active, so I have to force quit each time.

Using Mac OSX 10.12.5

**Comment by IndrekV** [comment] 2017-06-19 11:47
@mtsweir Can you confirm that this started happening recently (with one of the latest releases) or has the issue appeared also before the latest release. Also it would help if you could send feedback from the app right after the crash or freeze. Feedback from the app sends us logs so we can see what is causing this issue.

**Comment by mtsweir** [comment] 2017-06-19 21:06
ok will do, from what I see so far is that if left tracking for long periods it seems to be the issue. If I close it straight away it seems fine, as well as tracking for a short while. My normal tracking is over an hour, when I close the modal its fine but closing toggl itself the program remains open.

**Comment by ChrisARaymond** [comment] 2017-06-23 22:13
Have been experiencing a similar issue the past few days. Mac 10.12.5, toggl desktop 7.4.52. When it's been tracking all day, have to force quit desktop app.

**Comment by mtsweir** [comment] 2017-06-24 00:24
My version is: 7.4.47

**Comment by nicktoggl** [comment] 2017-06-27 02:14
/case/495771

**Comment by simonvomeyser** [comment] 2017-06-29 08:18
Experiencing the same issue :( Mac 10.12.5, Toggl Desktop App 7.4.52.

Closing the App with CMD+Q almost always causes a crash, App also prevents system shutdown if I don't close the active window (CMD+W) before.

Love the App though, use it every day. Thank you for your good work :)

**Comment by zdericnina** [comment] 2017-06-29 12:59
case with similar issue on both Mac and Win: 496865

**Comment by vedr4n** [comment] 2017-07-04 13:12
Another affected user: 500915

**Comment by realjoshharrison** [comment] 2017-07-04 14:26
@IndrekV I just sent feedback from the app [as requested](#issuecomment-309416726) and referenced this issue in with the report, hope that helps

**Comment by IndrekV** [comment] 2017-07-12 20:51
I think I've found the cause of this. It seems that one of the background tasks is failing to close when the app is quitting. I will do some more tests and work on a fix. Thank you guys for all the details.

**Comment by mtsweir** [comment] 2017-07-12 20:57
Yes does seem like this could be the cause, good find IndrekV

**Comment by ApocalypticFish** [comment] 2017-07-17 06:53
case/505574 also experiencing the same issue and on version 7.4.52 logs attached to the case.

**Closed** 2017-07-28 12:29 UTC
Labels: bug, macOs

**Comment by gusrub** [comment] 2017-08-08 18:13
Is there an ETA for this do be deployed on the installers? I click the "check for update" option on the app but there are no updates.

**Comment by IndrekV** [comment] 2017-08-09 21:36
I just pushed out new beta version (7.4.58) https://github.com/toggl/toggldesktop/releases/tag/v7.4.58

Get it by changing the channel to beta in about view.

**Comment by gusrub** [comment] 2017-08-09 22:37
@IndrekV Oh nevermind, I went to the releases page on github and downloaded the latest tag manually, thanks a bunch anyway!

**Comment by jwaldenllc** [comment] 2017-08-22 02:57
7.4.58 resolved this issue for me, but the update wasn't deployed when I used the 'check for update' function.
